package com.path.atm.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class GTW_ATM_ISO_NET_MSG_FLDSVO extends BaseVO {
    /**
     * This field corresponds to the database column GTW_ATM_ISO_NET_MSG_FLDS.NET_MSG_FLD_ID
     */
    private BigDecimal NET_MSG_FLD_ID;

    /**
     * This field corresponds to the database column GTW_ATM_ISO_NET_MSG_FLDS.ISO_MSG_DEF_ID
     */
    private BigDecimal ISO_MSG_DEF_ID;

    /**
     * This field corresponds to the database column GTW_ATM_ISO_NET_MSG_FLDS.FIELD_CODE
     */
    private BigDecimal FIELD_CODE;

    /**
     * This field corresponds to the database column GTW_ATM_ISO_NET_MSG_FLDS.REQUEST_FIELD_YN
     */
    private String REQUEST_FIELD_YN;

    /**
     * This field corresponds to the database column GTW_ATM_ISO_NET_MSG_FLDS.EXPRESSION
     */
    private String EXPRESSION;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ISO_NET_MSG_FLDS.NET_MSG_FLD_ID
     *
     * @return the value of GTW_ATM_ISO_NET_MSG_FLDS.NET_MSG_FLD_ID
     */
    public BigDecimal getNET_MSG_FLD_ID() {
        return NET_MSG_FLD_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ISO_NET_MSG_FLDS.NET_MSG_FLD_ID
     *
     * @param NET_MSG_FLD_ID the value for GTW_ATM_ISO_NET_MSG_FLDS.NET_MSG_FLD_ID
     */
    public void setNET_MSG_FLD_ID(BigDecimal NET_MSG_FLD_ID) {
        this.NET_MSG_FLD_ID = NET_MSG_FLD_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ISO_NET_MSG_FLDS.ISO_MSG_DEF_ID
     *
     * @return the value of GTW_ATM_ISO_NET_MSG_FLDS.ISO_MSG_DEF_ID
     */
    public BigDecimal getISO_MSG_DEF_ID() {
        return ISO_MSG_DEF_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ISO_NET_MSG_FLDS.ISO_MSG_DEF_ID
     *
     * @param ISO_MSG_DEF_ID the value for GTW_ATM_ISO_NET_MSG_FLDS.ISO_MSG_DEF_ID
     */
    public void setISO_MSG_DEF_ID(BigDecimal ISO_MSG_DEF_ID) {
        this.ISO_MSG_DEF_ID = ISO_MSG_DEF_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ISO_NET_MSG_FLDS.FIELD_CODE
     *
     * @return the value of GTW_ATM_ISO_NET_MSG_FLDS.FIELD_CODE
     */
    public BigDecimal getFIELD_CODE() {
        return FIELD_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ISO_NET_MSG_FLDS.FIELD_CODE
     *
     * @param FIELD_CODE the value for GTW_ATM_ISO_NET_MSG_FLDS.FIELD_CODE
     */
    public void setFIELD_CODE(BigDecimal FIELD_CODE) {
        this.FIELD_CODE = FIELD_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ISO_NET_MSG_FLDS.REQUEST_FIELD_YN
     *
     * @return the value of GTW_ATM_ISO_NET_MSG_FLDS.REQUEST_FIELD_YN
     */
    public String getREQUEST_FIELD_YN() {
        return REQUEST_FIELD_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ISO_NET_MSG_FLDS.REQUEST_FIELD_YN
     *
     * @param REQUEST_FIELD_YN the value for GTW_ATM_ISO_NET_MSG_FLDS.REQUEST_FIELD_YN
     */
    public void setREQUEST_FIELD_YN(String REQUEST_FIELD_YN) {
        this.REQUEST_FIELD_YN = REQUEST_FIELD_YN == null ? null : REQUEST_FIELD_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ISO_NET_MSG_FLDS.EXPRESSION
     *
     * @return the value of GTW_ATM_ISO_NET_MSG_FLDS.EXPRESSION
     */
    public String getEXPRESSION() {
        return EXPRESSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ISO_NET_MSG_FLDS.EXPRESSION
     *
     * @param EXPRESSION the value for GTW_ATM_ISO_NET_MSG_FLDS.EXPRESSION
     */
    public void setEXPRESSION(String EXPRESSION) {
        this.EXPRESSION = EXPRESSION == null ? null : EXPRESSION.trim();
    }
}