package com.path.atm.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class GTW_PWS_TEST_MASTERVO extends BaseVO {
    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TEST_MASTER.CONFIG_ID
     */
    private BigDecimal CONFIG_ID;

    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TEST_MASTER.CONFIG_NAME
     */
    private String CONFIG_NAME;

    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TEST_MASTER.APPLICATION_NAME
     */
    private String APPLICATION_NAME;

    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TEST_MASTER.OPERATION_NAME
     */
    private String OPERATION_NAME;

    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TEST_MASTER.ENDPOINT_NAME
     */
    private String ENDPOINT_NAME;

    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TEST_MASTER.CONFIG_REQUEST
     */
    private String CONFIG_REQUEST;

    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TEST_MASTER.CONFIG_RESPONSE
     */
    private String CONFIG_RESPONSE;

    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TEST_MASTER.JSON_REQUEST
     */
    private String JSON_REQUEST;

    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TEST_MASTER.JSON_FILTERED_REQUEST
     */
    private String JSON_FILTERED_REQUEST;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TEST_MASTER.CONFIG_ID
     *
     * @return the value of DGTL_GTW_PWS_TEST_MASTER.CONFIG_ID
     */
    public BigDecimal getCONFIG_ID() {
        return CONFIG_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TEST_MASTER.CONFIG_ID
     *
     * @param CONFIG_ID the value for DGTL_GTW_PWS_TEST_MASTER.CONFIG_ID
     */
    public void setCONFIG_ID(BigDecimal CONFIG_ID) {
        this.CONFIG_ID = CONFIG_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TEST_MASTER.CONFIG_NAME
     *
     * @return the value of DGTL_GTW_PWS_TEST_MASTER.CONFIG_NAME
     */
    public String getCONFIG_NAME() {
        return CONFIG_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TEST_MASTER.CONFIG_NAME
     *
     * @param CONFIG_NAME the value for DGTL_GTW_PWS_TEST_MASTER.CONFIG_NAME
     */
    public void setCONFIG_NAME(String CONFIG_NAME) {
        this.CONFIG_NAME = CONFIG_NAME == null ? null : CONFIG_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TEST_MASTER.APPLICATION_NAME
     *
     * @return the value of DGTL_GTW_PWS_TEST_MASTER.APPLICATION_NAME
     */
    public String getAPPLICATION_NAME() {
        return APPLICATION_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TEST_MASTER.APPLICATION_NAME
     *
     * @param APPLICATION_NAME the value for DGTL_GTW_PWS_TEST_MASTER.APPLICATION_NAME
     */
    public void setAPPLICATION_NAME(String APPLICATION_NAME) {
        this.APPLICATION_NAME = APPLICATION_NAME == null ? null : APPLICATION_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TEST_MASTER.OPERATION_NAME
     *
     * @return the value of DGTL_GTW_PWS_TEST_MASTER.OPERATION_NAME
     */
    public String getOPERATION_NAME() {
        return OPERATION_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TEST_MASTER.OPERATION_NAME
     *
     * @param OPERATION_NAME the value for DGTL_GTW_PWS_TEST_MASTER.OPERATION_NAME
     */
    public void setOPERATION_NAME(String OPERATION_NAME) {
        this.OPERATION_NAME = OPERATION_NAME == null ? null : OPERATION_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TEST_MASTER.ENDPOINT_NAME
     *
     * @return the value of DGTL_GTW_PWS_TEST_MASTER.ENDPOINT_NAME
     */
    public String getENDPOINT_NAME() {
        return ENDPOINT_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TEST_MASTER.ENDPOINT_NAME
     *
     * @param ENDPOINT_NAME the value for DGTL_GTW_PWS_TEST_MASTER.ENDPOINT_NAME
     */
    public void setENDPOINT_NAME(String ENDPOINT_NAME) {
        this.ENDPOINT_NAME = ENDPOINT_NAME == null ? null : ENDPOINT_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TEST_MASTER.CONFIG_REQUEST
     *
     * @return the value of DGTL_GTW_PWS_TEST_MASTER.CONFIG_REQUEST
     */
    public String getCONFIG_REQUEST() {
        return CONFIG_REQUEST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TEST_MASTER.CONFIG_REQUEST
     *
     * @param CONFIG_REQUEST the value for DGTL_GTW_PWS_TEST_MASTER.CONFIG_REQUEST
     */
    public void setCONFIG_REQUEST(String CONFIG_REQUEST) {
        this.CONFIG_REQUEST = CONFIG_REQUEST == null ? null : CONFIG_REQUEST.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TEST_MASTER.CONFIG_RESPONSE
     *
     * @return the value of DGTL_GTW_PWS_TEST_MASTER.CONFIG_RESPONSE
     */
    public String getCONFIG_RESPONSE() {
        return CONFIG_RESPONSE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TEST_MASTER.CONFIG_RESPONSE
     *
     * @param CONFIG_RESPONSE the value for DGTL_GTW_PWS_TEST_MASTER.CONFIG_RESPONSE
     */
    public void setCONFIG_RESPONSE(String CONFIG_RESPONSE) {
        this.CONFIG_RESPONSE = CONFIG_RESPONSE == null ? null : CONFIG_RESPONSE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TEST_MASTER.JSON_REQUEST
     *
     * @return the value of DGTL_GTW_PWS_TEST_MASTER.JSON_REQUEST
     */
    public String getJSON_REQUEST() {
        return JSON_REQUEST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TEST_MASTER.JSON_REQUEST
     *
     * @param JSON_REQUEST the value for DGTL_GTW_PWS_TEST_MASTER.JSON_REQUEST
     */
    public void setJSON_REQUEST(String JSON_REQUEST) {
        this.JSON_REQUEST = JSON_REQUEST == null ? null : JSON_REQUEST.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TEST_MASTER.JSON_FILTERED_REQUEST
     *
     * @return the value of DGTL_GTW_PWS_TEST_MASTER.JSON_FILTERED_REQUEST
     */
    public String getJSON_FILTERED_REQUEST() {
        return JSON_FILTERED_REQUEST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TEST_MASTER.JSON_FILTERED_REQUEST
     *
     * @param JSON_FILTERED_REQUEST the value for DGTL_GTW_PWS_TEST_MASTER.JSON_FILTERED_REQUEST
     */
    public void setJSON_FILTERED_REQUEST(String JSON_FILTERED_REQUEST) {
        this.JSON_FILTERED_REQUEST = JSON_FILTERED_REQUEST == null ? null : JSON_FILTERED_REQUEST.trim();
    }
}