package com.path.atm.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class GTW_ATM_ACQUIRER_TRX_TYPEVO extends BaseVO {
    /**
     * This field corresponds to the database column GTW_ATM_ACQUIRER_TRX_TYPE.TRX_TYPE_ID
     */
    private BigDecimal TRX_TYPE_ID;

    /**
     * This field corresponds to the database column GTW_ATM_ACQUIRER_TRX_TYPE.ACQUIRER_ID
     */
    private BigDecimal ACQUIRER_ID;

    /**
     * This field corresponds to the database column GTW_ATM_ACQUIRER_TRX_TYPE.TRX_TYPE
     */
    private BigDecimal TRX_TYPE;

    /**
     * This field corresponds to the database column GTW_ATM_ACQUIRER_TRX_TYPE.TRX_EXPRESSION
     */
    private String TRX_EXPRESSION;

    /**
     * This field corresponds to the database column GTW_ATM_ACQUIRER_TRX_TYPE.CHARGES_TRX_TYPE
     */
    private BigDecimal CHARGES_TRX_TYPE;

    /**
     * This field corresponds to the database column GTW_ATM_ACQUIRER_TRX_TYPE.CHARGES_TRX_EXPRESSION
     */
    private String CHARGES_TRX_EXPRESSION;
    
    /**
     * This field corresponds to the database column GTW_ATM_ACQUIRER_TRX_TYPE.DESCRIPTION
     */
    private String DESCRIPTION;

    /**
     * This field corresponds to the database column GTW_ATM_ACQUIRER_TRX_TYPE.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column GTW_ATM_ACQUIRER_TRX_TYPE.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column GTW_ATM_ACQUIRER_TRX_TYPE.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column GTW_ATM_ACQUIRER_TRX_TYPE.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ACQUIRER_TRX_TYPE.TRX_TYPE_ID
     *
     * @return the value of GTW_ATM_ACQUIRER_TRX_TYPE.TRX_TYPE_ID
     */
    public BigDecimal getTRX_TYPE_ID() {
        return TRX_TYPE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ACQUIRER_TRX_TYPE.TRX_TYPE_ID
     *
     * @param TRX_TYPE_ID the value for GTW_ATM_ACQUIRER_TRX_TYPE.TRX_TYPE_ID
     */
    public void setTRX_TYPE_ID(BigDecimal TRX_TYPE_ID) {
        this.TRX_TYPE_ID = TRX_TYPE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ACQUIRER_TRX_TYPE.ACQUIRER_ID
     *
     * @return the value of GTW_ATM_ACQUIRER_TRX_TYPE.ACQUIRER_ID
     */
    public BigDecimal getACQUIRER_ID() {
        return ACQUIRER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ACQUIRER_TRX_TYPE.ACQUIRER_ID
     *
     * @param ACQUIRER_ID the value for GTW_ATM_ACQUIRER_TRX_TYPE.ACQUIRER_ID
     */
    public void setACQUIRER_ID(BigDecimal ACQUIRER_ID) {
        this.ACQUIRER_ID = ACQUIRER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ACQUIRER_TRX_TYPE.TRX_TYPE
     *
     * @return the value of GTW_ATM_ACQUIRER_TRX_TYPE.TRX_TYPE
     */
    public BigDecimal getTRX_TYPE() {
        return TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ACQUIRER_TRX_TYPE.TRX_TYPE
     *
     * @param TRX_TYPE the value for GTW_ATM_ACQUIRER_TRX_TYPE.TRX_TYPE
     */
    public void setTRX_TYPE(BigDecimal TRX_TYPE) {
        this.TRX_TYPE = TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ACQUIRER_TRX_TYPE.TRX_EXPRESSION
     *
     * @return the value of GTW_ATM_ACQUIRER_TRX_TYPE.TRX_EXPRESSION
     */
    public String getTRX_EXPRESSION() {
        return TRX_EXPRESSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ACQUIRER_TRX_TYPE.TRX_EXPRESSION
     *
     * @param TRX_EXPRESSION the value for GTW_ATM_ACQUIRER_TRX_TYPE.TRX_EXPRESSION
     */
    public void setTRX_EXPRESSION(String TRX_EXPRESSION) {
        this.TRX_EXPRESSION = TRX_EXPRESSION == null ? null : TRX_EXPRESSION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ACQUIRER_TRX_TYPE.CHARGES_TRX_TYPE
     *
     * @return the value of GTW_ATM_ACQUIRER_TRX_TYPE.CHARGES_TRX_TYPE
     */
    public BigDecimal getCHARGES_TRX_TYPE() {
        return CHARGES_TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ACQUIRER_TRX_TYPE.CHARGES_TRX_TYPE
     *
     * @param CHARGES_TRX_TYPE the value for GTW_ATM_ACQUIRER_TRX_TYPE.CHARGES_TRX_TYPE
     */
    public void setCHARGES_TRX_TYPE(BigDecimal CHARGES_TRX_TYPE) {
        this.CHARGES_TRX_TYPE = CHARGES_TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ACQUIRER_TRX_TYPE.CHARGES_TRX_EXPRESSION
     *
     * @return the value of GTW_ATM_ACQUIRER_TRX_TYPE.CHARGES_TRX_EXPRESSION
     */
    public String getCHARGES_TRX_EXPRESSION() {
        return CHARGES_TRX_EXPRESSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ACQUIRER_TRX_TYPE.CHARGES_TRX_EXPRESSION
     *
     * @param CHARGES_TRX_EXPRESSION the value for GTW_ATM_ACQUIRER_TRX_TYPE.CHARGES_TRX_EXPRESSION
     */
    public void setCHARGES_TRX_EXPRESSION(String CHARGES_TRX_EXPRESSION) {
        this.CHARGES_TRX_EXPRESSION = CHARGES_TRX_EXPRESSION == null ? null : CHARGES_TRX_EXPRESSION.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ACQUIRER_TRX_TYPE.DESCRIPTION
     *
     * @return the value of GTW_ATM_ACQUIRER_TRX_TYPE.DESCRIPTION
     */
    public String getDESCRIPTION()
    {
        return DESCRIPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ACQUIRER_TRX_TYPE.DESCRIPTION
     *
     * @param DESCRIPTION the value for GTW_ATM_ACQUIRER_TRX_TYPE.DESCRIPTION
     */
    public void setDESCRIPTION(String DESCRIPTION)
    {
	this.DESCRIPTION = DESCRIPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ACQUIRER_TRX_TYPE.CREATED_BY
     *
     * @return the value of GTW_ATM_ACQUIRER_TRX_TYPE.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ACQUIRER_TRX_TYPE.CREATED_BY
     *
     * @param CREATED_BY the value for GTW_ATM_ACQUIRER_TRX_TYPE.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ACQUIRER_TRX_TYPE.CREATED_DATE
     *
     * @return the value of GTW_ATM_ACQUIRER_TRX_TYPE.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ACQUIRER_TRX_TYPE.CREATED_DATE
     *
     * @param CREATED_DATE the value for GTW_ATM_ACQUIRER_TRX_TYPE.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ACQUIRER_TRX_TYPE.MODIFIED_BY
     *
     * @return the value of GTW_ATM_ACQUIRER_TRX_TYPE.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ACQUIRER_TRX_TYPE.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for GTW_ATM_ACQUIRER_TRX_TYPE.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ACQUIRER_TRX_TYPE.MODIFIED_DATE
     *
     * @return the value of GTW_ATM_ACQUIRER_TRX_TYPE.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ACQUIRER_TRX_TYPE.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for GTW_ATM_ACQUIRER_TRX_TYPE.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }
}