package com.path.atm.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class GTW_PWS_TEST_DETAILSVO extends BaseVO {
    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TEST_DETAILS.CONFIG_ID
     */
    private BigDecimal CONFIG_ID;

    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TEST_DETAILS.FIELD_ROW_ID
     */
    private String FIELD_ROW_ID;

    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TEST_DETAILS.VALUE
     */
    private String VALUE;

    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TEST_DETAILS.FIELD_TYPE
     */
    private String FIELD_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TEST_DETAILS.CONFIG_ID
     *
     * @return the value of DGTL_GTW_PWS_TEST_DETAILS.CONFIG_ID
     */
    public BigDecimal getCONFIG_ID() {
        return CONFIG_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TEST_DETAILS.CONFIG_ID
     *
     * @param CONFIG_ID the value for DGTL_GTW_PWS_TEST_DETAILS.CONFIG_ID
     */
    public void setCONFIG_ID(BigDecimal CONFIG_ID) {
        this.CONFIG_ID = CONFIG_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TEST_DETAILS.FIELD_ROW_ID
     *
     * @return the value of DGTL_GTW_PWS_TEST_DETAILS.FIELD_ROW_ID
     */
    public String getFIELD_ROW_ID() {
        return FIELD_ROW_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TEST_DETAILS.FIELD_ROW_ID
     *
     * @param FIELD_ROW_ID the value for DGTL_GTW_PWS_TEST_DETAILS.FIELD_ROW_ID
     */
    public void setFIELD_ROW_ID(String FIELD_ROW_ID) {
        this.FIELD_ROW_ID = FIELD_ROW_ID == null ? null : FIELD_ROW_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TEST_DETAILS.VALUE
     *
     * @return the value of DGTL_GTW_PWS_TEST_DETAILS.VALUE
     */
    public String getVALUE() {
        return VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TEST_DETAILS.VALUE
     *
     * @param VALUE the value for DGTL_GTW_PWS_TEST_DETAILS.VALUE
     */
    public void setVALUE(String VALUE) {
        this.VALUE = VALUE == null ? null : VALUE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TEST_DETAILS.FIELD_TYPE
     *
     * @return the value of DGTL_GTW_PWS_TEST_DETAILS.FIELD_TYPE
     */
    public String getFIELD_TYPE() {
        return FIELD_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TEST_DETAILS.FIELD_TYPE
     *
     * @param FIELD_TYPE the value for DGTL_GTW_PWS_TEST_DETAILS.FIELD_TYPE
     */
    public void setFIELD_TYPE(String FIELD_TYPE) {
        this.FIELD_TYPE = FIELD_TYPE == null ? null : FIELD_TYPE.trim();
    }
}