package com.path.atm.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class GTW_ATM_INT_ISO_MSGSVO extends BaseVO {
    /**
     * This field corresponds to the database column GTW_ATM_INT_ISO_MSGS.ATM_ISO_MSGS_CODE
     */
    private BigDecimal ATM_ISO_MSGS_CODE;

    /**
     * This field corresponds to the database column GTW_ATM_INT_ISO_MSGS.INTERFACE_CODE
     */
    private BigDecimal INTERFACE_CODE;

    /**
     * This field corresponds to the database column GTW_ATM_INT_ISO_MSGS.REQUEST_MTI
     */
    private String REQUEST_MTI;

    /**
     * This field corresponds to the database column GTW_ATM_INT_ISO_MSGS.REQUEST_BITMAP1
     */
    private String REQUEST_BITMAP1;

    /**
     * This field corresponds to the database column GTW_ATM_INT_ISO_MSGS.REQUEST_BITMAP2
     */
    private String REQUEST_BITMAP2;

    /**
     * This field corresponds to the database column GTW_ATM_INT_ISO_MSGS.RESPONSE_MTI
     */
    private String RESPONSE_MTI;

    /**
     * This field corresponds to the database column GTW_ATM_INT_ISO_MSGS.RESPONSE_BITMAP1
     */
    private String RESPONSE_BITMAP1;

    /**
     * This field corresponds to the database column GTW_ATM_INT_ISO_MSGS.RESPONSE_BITMAP2
     */
    private String RESPONSE_BITMAP2;

    /**
     * This field corresponds to the database column GTW_ATM_INT_ISO_MSGS.RESPONSE_EXPRESSION
     */
    private String RESPONSE_EXPRESSION;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INT_ISO_MSGS.ATM_ISO_MSGS_CODE
     *
     * @return the value of GTW_ATM_INT_ISO_MSGS.ATM_ISO_MSGS_CODE
     */
    public BigDecimal getATM_ISO_MSGS_CODE() {
        return ATM_ISO_MSGS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INT_ISO_MSGS.ATM_ISO_MSGS_CODE
     *
     * @param ATM_ISO_MSGS_CODE the value for GTW_ATM_INT_ISO_MSGS.ATM_ISO_MSGS_CODE
     */
    public void setATM_ISO_MSGS_CODE(BigDecimal ATM_ISO_MSGS_CODE) {
        this.ATM_ISO_MSGS_CODE = ATM_ISO_MSGS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INT_ISO_MSGS.INTERFACE_CODE
     *
     * @return the value of GTW_ATM_INT_ISO_MSGS.INTERFACE_CODE
     */
    public BigDecimal getINTERFACE_CODE() {
        return INTERFACE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INT_ISO_MSGS.INTERFACE_CODE
     *
     * @param INTERFACE_CODE the value for GTW_ATM_INT_ISO_MSGS.INTERFACE_CODE
     */
    public void setINTERFACE_CODE(BigDecimal INTERFACE_CODE) {
        this.INTERFACE_CODE = INTERFACE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INT_ISO_MSGS.REQUEST_MTI
     *
     * @return the value of GTW_ATM_INT_ISO_MSGS.REQUEST_MTI
     */
    public String getREQUEST_MTI() {
        return REQUEST_MTI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INT_ISO_MSGS.REQUEST_MTI
     *
     * @param REQUEST_MTI the value for GTW_ATM_INT_ISO_MSGS.REQUEST_MTI
     */
    public void setREQUEST_MTI(String REQUEST_MTI) {
        this.REQUEST_MTI = REQUEST_MTI == null ? null : REQUEST_MTI.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INT_ISO_MSGS.REQUEST_BITMAP1
     *
     * @return the value of GTW_ATM_INT_ISO_MSGS.REQUEST_BITMAP1
     */
    public String getREQUEST_BITMAP1() {
        return REQUEST_BITMAP1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INT_ISO_MSGS.REQUEST_BITMAP1
     *
     * @param REQUEST_BITMAP1 the value for GTW_ATM_INT_ISO_MSGS.REQUEST_BITMAP1
     */
    public void setREQUEST_BITMAP1(String REQUEST_BITMAP1) {
        this.REQUEST_BITMAP1 = REQUEST_BITMAP1 == null ? null : REQUEST_BITMAP1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INT_ISO_MSGS.REQUEST_BITMAP2
     *
     * @return the value of GTW_ATM_INT_ISO_MSGS.REQUEST_BITMAP2
     */
    public String getREQUEST_BITMAP2() {
        return REQUEST_BITMAP2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INT_ISO_MSGS.REQUEST_BITMAP2
     *
     * @param REQUEST_BITMAP2 the value for GTW_ATM_INT_ISO_MSGS.REQUEST_BITMAP2
     */
    public void setREQUEST_BITMAP2(String REQUEST_BITMAP2) {
        this.REQUEST_BITMAP2 = REQUEST_BITMAP2 == null ? null : REQUEST_BITMAP2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INT_ISO_MSGS.RESPONSE_MTI
     *
     * @return the value of GTW_ATM_INT_ISO_MSGS.RESPONSE_MTI
     */
    public String getRESPONSE_MTI() {
        return RESPONSE_MTI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INT_ISO_MSGS.RESPONSE_MTI
     *
     * @param RESPONSE_MTI the value for GTW_ATM_INT_ISO_MSGS.RESPONSE_MTI
     */
    public void setRESPONSE_MTI(String RESPONSE_MTI) {
        this.RESPONSE_MTI = RESPONSE_MTI == null ? null : RESPONSE_MTI.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INT_ISO_MSGS.RESPONSE_BITMAP1
     *
     * @return the value of GTW_ATM_INT_ISO_MSGS.RESPONSE_BITMAP1
     */
    public String getRESPONSE_BITMAP1() {
        return RESPONSE_BITMAP1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INT_ISO_MSGS.RESPONSE_BITMAP1
     *
     * @param RESPONSE_BITMAP1 the value for GTW_ATM_INT_ISO_MSGS.RESPONSE_BITMAP1
     */
    public void setRESPONSE_BITMAP1(String RESPONSE_BITMAP1) {
        this.RESPONSE_BITMAP1 = RESPONSE_BITMAP1 == null ? null : RESPONSE_BITMAP1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INT_ISO_MSGS.RESPONSE_BITMAP2
     *
     * @return the value of GTW_ATM_INT_ISO_MSGS.RESPONSE_BITMAP2
     */
    public String getRESPONSE_BITMAP2() {
        return RESPONSE_BITMAP2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INT_ISO_MSGS.RESPONSE_BITMAP2
     *
     * @param RESPONSE_BITMAP2 the value for GTW_ATM_INT_ISO_MSGS.RESPONSE_BITMAP2
     */
    public void setRESPONSE_BITMAP2(String RESPONSE_BITMAP2) {
        this.RESPONSE_BITMAP2 = RESPONSE_BITMAP2 == null ? null : RESPONSE_BITMAP2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INT_ISO_MSGS.RESPONSE_EXPRESSION
     *
     * @return the value of GTW_ATM_INT_ISO_MSGS.RESPONSE_EXPRESSION
     */
    public String getRESPONSE_EXPRESSION() {
        return RESPONSE_EXPRESSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INT_ISO_MSGS.RESPONSE_EXPRESSION
     *
     * @param RESPONSE_EXPRESSION the value for GTW_ATM_INT_ISO_MSGS.RESPONSE_EXPRESSION
     */
    public void setRESPONSE_EXPRESSION(String RESPONSE_EXPRESSION) {
        this.RESPONSE_EXPRESSION = RESPONSE_EXPRESSION == null ? null : RESPONSE_EXPRESSION.trim();
    }
}