package com.path.atm.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class GTW_PWS_TMPLT_DETVO extends BaseVO {
    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TMPLT_DET.APP_NAME
     */
    private String APP_NAME;

    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TMPLT_DET.OPERATION
     */
    private String OPERATION;

    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TMPLT_DET.TEMPLATE_ID
     */
    private BigDecimal TEMPLATE_ID;

    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TMPLT_DET.WS_NAME
     */
    private String WS_NAME;

    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TMPLT_DET.EXCLUDE_ACCESS_YN
     */
    private String EXCLUDE_ACCESS_YN;

    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TMPLT_DET.TYPE
     */
    private String TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TMPLT_DET.APP_NAME
     *
     * @return the value of DGTL_GTW_PWS_TMPLT_DET.APP_NAME
     */
    public String getAPP_NAME() {
        return APP_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TMPLT_DET.APP_NAME
     *
     * @param APP_NAME the value for DGTL_GTW_PWS_TMPLT_DET.APP_NAME
     */
    public void setAPP_NAME(String APP_NAME) {
        this.APP_NAME = APP_NAME == null ? null : APP_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TMPLT_DET.OPERATION
     *
     * @return the value of DGTL_GTW_PWS_TMPLT_DET.OPERATION
     */
    public String getOPERATION() {
        return OPERATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TMPLT_DET.OPERATION
     *
     * @param OPERATION the value for DGTL_GTW_PWS_TMPLT_DET.OPERATION
     */
    public void setOPERATION(String OPERATION) {
        this.OPERATION = OPERATION == null ? null : OPERATION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TMPLT_DET.TEMPLATE_ID
     *
     * @return the value of DGTL_GTW_PWS_TMPLT_DET.TEMPLATE_ID
     */
    public BigDecimal getTEMPLATE_ID() {
        return TEMPLATE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TMPLT_DET.TEMPLATE_ID
     *
     * @param TEMPLATE_ID the value for DGTL_GTW_PWS_TMPLT_DET.TEMPLATE_ID
     */
    public void setTEMPLATE_ID(BigDecimal TEMPLATE_ID) {
        this.TEMPLATE_ID = TEMPLATE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TMPLT_DET.WS_NAME
     *
     * @return the value of DGTL_GTW_PWS_TMPLT_DET.WS_NAME
     */
    public String getWS_NAME() {
        return WS_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TMPLT_DET.WS_NAME
     *
     * @param WS_NAME the value for DGTL_GTW_PWS_TMPLT_DET.WS_NAME
     */
    public void setWS_NAME(String WS_NAME) {
        this.WS_NAME = WS_NAME == null ? null : WS_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TMPLT_DET.EXCLUDE_ACCESS_YN
     *
     * @return the value of DGTL_GTW_PWS_TMPLT_DET.EXCLUDE_ACCESS_YN
     */
    public String getEXCLUDE_ACCESS_YN() {
        return EXCLUDE_ACCESS_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TMPLT_DET.EXCLUDE_ACCESS_YN
     *
     * @param EXCLUDE_ACCESS_YN the value for DGTL_GTW_PWS_TMPLT_DET.EXCLUDE_ACCESS_YN
     */
    public void setEXCLUDE_ACCESS_YN(String EXCLUDE_ACCESS_YN) {
        this.EXCLUDE_ACCESS_YN = EXCLUDE_ACCESS_YN == null ? null : EXCLUDE_ACCESS_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TMPLT_DET.TYPE
     *
     * @return the value of DGTL_GTW_PWS_TMPLT_DET.TYPE
     */
    public String getTYPE() {
        return TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TMPLT_DET.TYPE
     *
     * @param TYPE the value for DGTL_GTW_PWS_TMPLT_DET.TYPE
     */
    public void setTYPE(String TYPE) {
        this.TYPE = TYPE == null ? null : TYPE.trim();
    }
}