package com.path.atm.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class GTW_PWS_TMPLT_MASTERVO extends BaseVO {
    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TMPLT_MASTER.TEMPLATE_ID
     */
    private BigDecimal TEMPLATE_ID;

    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TMPLT_MASTER.TEMPLATE_DESC
     */
    private String TEMPLATE_DESC;

    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TMPLT_MASTER.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TMPLT_MASTER.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TMPLT_MASTER.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TMPLT_MASTER.SERVER_CREATED_DATE
     */
    private Date SERVER_CREATED_DATE;

    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TMPLT_MASTER.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TMPLT_MASTER.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TMPLT_MASTER.SERVER_MODIFIED_DATE
     */
    private Date SERVER_MODIFIED_DATE;

    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TMPLT_MASTER.APPROVED_BY
     */
    private String APPROVED_BY;

    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TMPLT_MASTER.APPROVED_DATE
     */
    private Date APPROVED_DATE;

    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TMPLT_MASTER.SERVER_APPROVED_DATE
     */
    private Date SERVER_APPROVED_DATE;

    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TMPLT_MASTER.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TMPLT_MASTER.DELETED_DATE
     */
    private Date DELETED_DATE;

    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TMPLT_MASTER.SERVER_DELETED_DATE
     */
    private Date SERVER_DELETED_DATE;

    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TMPLT_MASTER.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TMPLT_MASTER.TEMPLATE_ID
     *
     * @return the value of DGTL_GTW_PWS_TMPLT_MASTER.TEMPLATE_ID
     */
    public BigDecimal getTEMPLATE_ID() {
        return TEMPLATE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TMPLT_MASTER.TEMPLATE_ID
     *
     * @param TEMPLATE_ID the value for DGTL_GTW_PWS_TMPLT_MASTER.TEMPLATE_ID
     */
    public void setTEMPLATE_ID(BigDecimal TEMPLATE_ID) {
        this.TEMPLATE_ID = TEMPLATE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TMPLT_MASTER.TEMPLATE_DESC
     *
     * @return the value of DGTL_GTW_PWS_TMPLT_MASTER.TEMPLATE_DESC
     */
    public String getTEMPLATE_DESC() {
        return TEMPLATE_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TMPLT_MASTER.TEMPLATE_DESC
     *
     * @param TEMPLATE_DESC the value for DGTL_GTW_PWS_TMPLT_MASTER.TEMPLATE_DESC
     */
    public void setTEMPLATE_DESC(String TEMPLATE_DESC) {
        this.TEMPLATE_DESC = TEMPLATE_DESC == null ? null : TEMPLATE_DESC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TMPLT_MASTER.STATUS
     *
     * @return the value of DGTL_GTW_PWS_TMPLT_MASTER.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TMPLT_MASTER.STATUS
     *
     * @param STATUS the value for DGTL_GTW_PWS_TMPLT_MASTER.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TMPLT_MASTER.CREATED_BY
     *
     * @return the value of DGTL_GTW_PWS_TMPLT_MASTER.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TMPLT_MASTER.CREATED_BY
     *
     * @param CREATED_BY the value for DGTL_GTW_PWS_TMPLT_MASTER.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TMPLT_MASTER.CREATED_DATE
     *
     * @return the value of DGTL_GTW_PWS_TMPLT_MASTER.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TMPLT_MASTER.CREATED_DATE
     *
     * @param CREATED_DATE the value for DGTL_GTW_PWS_TMPLT_MASTER.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TMPLT_MASTER.SERVER_CREATED_DATE
     *
     * @return the value of DGTL_GTW_PWS_TMPLT_MASTER.SERVER_CREATED_DATE
     */
    public Date getSERVER_CREATED_DATE() {
        return SERVER_CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TMPLT_MASTER.SERVER_CREATED_DATE
     *
     * @param SERVER_CREATED_DATE the value for DGTL_GTW_PWS_TMPLT_MASTER.SERVER_CREATED_DATE
     */
    public void setSERVER_CREATED_DATE(Date SERVER_CREATED_DATE) {
        this.SERVER_CREATED_DATE = SERVER_CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TMPLT_MASTER.MODIFIED_BY
     *
     * @return the value of DGTL_GTW_PWS_TMPLT_MASTER.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TMPLT_MASTER.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for DGTL_GTW_PWS_TMPLT_MASTER.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TMPLT_MASTER.MODIFIED_DATE
     *
     * @return the value of DGTL_GTW_PWS_TMPLT_MASTER.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TMPLT_MASTER.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for DGTL_GTW_PWS_TMPLT_MASTER.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TMPLT_MASTER.SERVER_MODIFIED_DATE
     *
     * @return the value of DGTL_GTW_PWS_TMPLT_MASTER.SERVER_MODIFIED_DATE
     */
    public Date getSERVER_MODIFIED_DATE() {
        return SERVER_MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TMPLT_MASTER.SERVER_MODIFIED_DATE
     *
     * @param SERVER_MODIFIED_DATE the value for DGTL_GTW_PWS_TMPLT_MASTER.SERVER_MODIFIED_DATE
     */
    public void setSERVER_MODIFIED_DATE(Date SERVER_MODIFIED_DATE) {
        this.SERVER_MODIFIED_DATE = SERVER_MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TMPLT_MASTER.APPROVED_BY
     *
     * @return the value of DGTL_GTW_PWS_TMPLT_MASTER.APPROVED_BY
     */
    public String getAPPROVED_BY() {
        return APPROVED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TMPLT_MASTER.APPROVED_BY
     *
     * @param APPROVED_BY the value for DGTL_GTW_PWS_TMPLT_MASTER.APPROVED_BY
     */
    public void setAPPROVED_BY(String APPROVED_BY) {
        this.APPROVED_BY = APPROVED_BY == null ? null : APPROVED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TMPLT_MASTER.APPROVED_DATE
     *
     * @return the value of DGTL_GTW_PWS_TMPLT_MASTER.APPROVED_DATE
     */
    public Date getAPPROVED_DATE() {
        return APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TMPLT_MASTER.APPROVED_DATE
     *
     * @param APPROVED_DATE the value for DGTL_GTW_PWS_TMPLT_MASTER.APPROVED_DATE
     */
    public void setAPPROVED_DATE(Date APPROVED_DATE) {
        this.APPROVED_DATE = APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TMPLT_MASTER.SERVER_APPROVED_DATE
     *
     * @return the value of DGTL_GTW_PWS_TMPLT_MASTER.SERVER_APPROVED_DATE
     */
    public Date getSERVER_APPROVED_DATE() {
        return SERVER_APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TMPLT_MASTER.SERVER_APPROVED_DATE
     *
     * @param SERVER_APPROVED_DATE the value for DGTL_GTW_PWS_TMPLT_MASTER.SERVER_APPROVED_DATE
     */
    public void setSERVER_APPROVED_DATE(Date SERVER_APPROVED_DATE) {
        this.SERVER_APPROVED_DATE = SERVER_APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TMPLT_MASTER.DELETED_BY
     *
     * @return the value of DGTL_GTW_PWS_TMPLT_MASTER.DELETED_BY
     */
    public String getDELETED_BY() {
        return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TMPLT_MASTER.DELETED_BY
     *
     * @param DELETED_BY the value for DGTL_GTW_PWS_TMPLT_MASTER.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY) {
        this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TMPLT_MASTER.DELETED_DATE
     *
     * @return the value of DGTL_GTW_PWS_TMPLT_MASTER.DELETED_DATE
     */
    public Date getDELETED_DATE() {
        return DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TMPLT_MASTER.DELETED_DATE
     *
     * @param DELETED_DATE the value for DGTL_GTW_PWS_TMPLT_MASTER.DELETED_DATE
     */
    public void setDELETED_DATE(Date DELETED_DATE) {
        this.DELETED_DATE = DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TMPLT_MASTER.SERVER_DELETED_DATE
     *
     * @return the value of DGTL_GTW_PWS_TMPLT_MASTER.SERVER_DELETED_DATE
     */
    public Date getSERVER_DELETED_DATE() {
        return SERVER_DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TMPLT_MASTER.SERVER_DELETED_DATE
     *
     * @param SERVER_DELETED_DATE the value for DGTL_GTW_PWS_TMPLT_MASTER.SERVER_DELETED_DATE
     */
    public void setSERVER_DELETED_DATE(Date SERVER_DELETED_DATE) {
        this.SERVER_DELETED_DATE = SERVER_DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TMPLT_MASTER.DATE_UPDATED
     *
     * @return the value of DGTL_GTW_PWS_TMPLT_MASTER.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TMPLT_MASTER.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for DGTL_GTW_PWS_TMPLT_MASTER.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }
}