package com.path.atm.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class GTW_ATM_ISO_MSG_DEFVO extends BaseVO {
    /**
     * This field corresponds to the database column GTW_ATM_ISO_MSG_DEF.ISO_MSG_DEF_ID
     */
    private BigDecimal ISO_MSG_DEF_ID;

    /**
     * This field corresponds to the database column GTW_ATM_ISO_MSG_DEF.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column GTW_ATM_ISO_MSG_DEF.DESCRIPTION
     */
    private String DESCRIPTION;

    /**
     * This field corresponds to the database column GTW_ATM_ISO_MSG_DEF.INTERFACE_CODE
     */
    private BigDecimal INTERFACE_CODE;

    /**
     * This field corresponds to the database column GTW_ATM_ISO_MSG_DEF.NETWORK_MESSAGE_YN
     */
    private String NETWORK_MESSAGE_YN;

    /**
     * This field corresponds to the database column GTW_ATM_ISO_MSG_DEF.ATM_ISO_MSGS_CODE
     */
    private BigDecimal ATM_ISO_MSGS_CODE;

    /**
     * This field corresponds to the database column GTW_ATM_ISO_MSG_DEF.PROCESS_CODE
     */
    private String PROCESS_CODE;

    /**
     * This field corresponds to the database column GTW_ATM_ISO_MSG_DEF.ADD_CRITERIA_EXPRESSION
     */
    private String ADD_CRITERIA_EXPRESSION;

    /**
     * This field corresponds to the database column GTW_ATM_ISO_MSG_DEF.MAPPING_ID
     */
    private BigDecimal MAPPING_ID;

    /**
     * This field corresponds to the database column GTW_ATM_ISO_MSG_DEF.NETWORK_MESSAGE_TYPE
     */
    private String NETWORK_MESSAGE_TYPE;

    /**
     * This field corresponds to the database column GTW_ATM_ISO_MSG_DEF.REQUEST_PRI_BITMAP
     */
    private String REQUEST_PRI_BITMAP;

    /**
     * This field corresponds to the database column GTW_ATM_ISO_MSG_DEF.REQUEST_SEC_BITMAP
     */
    private String REQUEST_SEC_BITMAP;

    /**
     * This field corresponds to the database column GTW_ATM_ISO_MSG_DEF.RESPONSE_PRI_BITMAP
     */
    private String RESPONSE_PRI_BITMAP;

    /**
     * This field corresponds to the database column GTW_ATM_ISO_MSG_DEF.RESPONSE_SEC_BITMAP
     */
    private String RESPONSE_SEC_BITMAP;

    /**
     * This field corresponds to the database column GTW_ATM_ISO_MSG_DEF.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column GTW_ATM_ISO_MSG_DEF.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column GTW_ATM_ISO_MSG_DEF.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column GTW_ATM_ISO_MSG_DEF.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ISO_MSG_DEF.ISO_MSG_DEF_ID
     *
     * @return the value of GTW_ATM_ISO_MSG_DEF.ISO_MSG_DEF_ID
     */
    public BigDecimal getISO_MSG_DEF_ID() {
        return ISO_MSG_DEF_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ISO_MSG_DEF.ISO_MSG_DEF_ID
     *
     * @param ISO_MSG_DEF_ID the value for GTW_ATM_ISO_MSG_DEF.ISO_MSG_DEF_ID
     */
    public void setISO_MSG_DEF_ID(BigDecimal ISO_MSG_DEF_ID) {
        this.ISO_MSG_DEF_ID = ISO_MSG_DEF_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ISO_MSG_DEF.COMP_CODE
     *
     * @return the value of GTW_ATM_ISO_MSG_DEF.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ISO_MSG_DEF.COMP_CODE
     *
     * @param COMP_CODE the value for GTW_ATM_ISO_MSG_DEF.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ISO_MSG_DEF.DESCRIPTION
     *
     * @return the value of GTW_ATM_ISO_MSG_DEF.DESCRIPTION
     */
    public String getDESCRIPTION() {
        return DESCRIPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ISO_MSG_DEF.DESCRIPTION
     *
     * @param DESCRIPTION the value for GTW_ATM_ISO_MSG_DEF.DESCRIPTION
     */
    public void setDESCRIPTION(String DESCRIPTION) {
        this.DESCRIPTION = DESCRIPTION == null ? null : DESCRIPTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ISO_MSG_DEF.INTERFACE_CODE
     *
     * @return the value of GTW_ATM_ISO_MSG_DEF.INTERFACE_CODE
     */
    public BigDecimal getINTERFACE_CODE() {
        return INTERFACE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ISO_MSG_DEF.INTERFACE_CODE
     *
     * @param INTERFACE_CODE the value for GTW_ATM_ISO_MSG_DEF.INTERFACE_CODE
     */
    public void setINTERFACE_CODE(BigDecimal INTERFACE_CODE) {
        this.INTERFACE_CODE = INTERFACE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ISO_MSG_DEF.NETWORK_MESSAGE_YN
     *
     * @return the value of GTW_ATM_ISO_MSG_DEF.NETWORK_MESSAGE_YN
     */
    public String getNETWORK_MESSAGE_YN() {
        return NETWORK_MESSAGE_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ISO_MSG_DEF.NETWORK_MESSAGE_YN
     *
     * @param NETWORK_MESSAGE_YN the value for GTW_ATM_ISO_MSG_DEF.NETWORK_MESSAGE_YN
     */
    public void setNETWORK_MESSAGE_YN(String NETWORK_MESSAGE_YN) {
        this.NETWORK_MESSAGE_YN = NETWORK_MESSAGE_YN == null ? null : NETWORK_MESSAGE_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ISO_MSG_DEF.ATM_ISO_MSGS_CODE
     *
     * @return the value of GTW_ATM_ISO_MSG_DEF.ATM_ISO_MSGS_CODE
     */
    public BigDecimal getATM_ISO_MSGS_CODE() {
        return ATM_ISO_MSGS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ISO_MSG_DEF.ATM_ISO_MSGS_CODE
     *
     * @param ATM_ISO_MSGS_CODE the value for GTW_ATM_ISO_MSG_DEF.ATM_ISO_MSGS_CODE
     */
    public void setATM_ISO_MSGS_CODE(BigDecimal ATM_ISO_MSGS_CODE) {
        this.ATM_ISO_MSGS_CODE = ATM_ISO_MSGS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ISO_MSG_DEF.PROCESS_CODE
     *
     * @return the value of GTW_ATM_ISO_MSG_DEF.PROCESS_CODE
     */
    public String getPROCESS_CODE() {
        return PROCESS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ISO_MSG_DEF.PROCESS_CODE
     *
     * @param PROCESS_CODE the value for GTW_ATM_ISO_MSG_DEF.PROCESS_CODE
     */
    public void setPROCESS_CODE(String PROCESS_CODE) {
        this.PROCESS_CODE = PROCESS_CODE == null ? null : PROCESS_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ISO_MSG_DEF.ADD_CRITERIA_EXPRESSION
     *
     * @return the value of GTW_ATM_ISO_MSG_DEF.ADD_CRITERIA_EXPRESSION
     */
    public String getADD_CRITERIA_EXPRESSION() {
        return ADD_CRITERIA_EXPRESSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ISO_MSG_DEF.ADD_CRITERIA_EXPRESSION
     *
     * @param ADD_CRITERIA_EXPRESSION the value for GTW_ATM_ISO_MSG_DEF.ADD_CRITERIA_EXPRESSION
     */
    public void setADD_CRITERIA_EXPRESSION(String ADD_CRITERIA_EXPRESSION) {
        this.ADD_CRITERIA_EXPRESSION = ADD_CRITERIA_EXPRESSION == null ? null : ADD_CRITERIA_EXPRESSION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ISO_MSG_DEF.MAPPING_ID
     *
     * @return the value of GTW_ATM_ISO_MSG_DEF.MAPPING_ID
     */
    public BigDecimal getMAPPING_ID() {
        return MAPPING_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ISO_MSG_DEF.MAPPING_ID
     *
     * @param MAPPING_ID the value for GTW_ATM_ISO_MSG_DEF.MAPPING_ID
     */
    public void setMAPPING_ID(BigDecimal MAPPING_ID) {
        this.MAPPING_ID = MAPPING_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ISO_MSG_DEF.NETWORK_MESSAGE_TYPE
     *
     * @return the value of GTW_ATM_ISO_MSG_DEF.NETWORK_MESSAGE_TYPE
     */
    public String getNETWORK_MESSAGE_TYPE() {
        return NETWORK_MESSAGE_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ISO_MSG_DEF.NETWORK_MESSAGE_TYPE
     *
     * @param NETWORK_MESSAGE_TYPE the value for GTW_ATM_ISO_MSG_DEF.NETWORK_MESSAGE_TYPE
     */
    public void setNETWORK_MESSAGE_TYPE(String NETWORK_MESSAGE_TYPE) {
        this.NETWORK_MESSAGE_TYPE = NETWORK_MESSAGE_TYPE == null ? null : NETWORK_MESSAGE_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ISO_MSG_DEF.REQUEST_PRI_BITMAP
     *
     * @return the value of GTW_ATM_ISO_MSG_DEF.REQUEST_PRI_BITMAP
     */
    public String getREQUEST_PRI_BITMAP() {
        return REQUEST_PRI_BITMAP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ISO_MSG_DEF.REQUEST_PRI_BITMAP
     *
     * @param REQUEST_PRI_BITMAP the value for GTW_ATM_ISO_MSG_DEF.REQUEST_PRI_BITMAP
     */
    public void setREQUEST_PRI_BITMAP(String REQUEST_PRI_BITMAP) {
        this.REQUEST_PRI_BITMAP = REQUEST_PRI_BITMAP == null ? null : REQUEST_PRI_BITMAP.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ISO_MSG_DEF.REQUEST_SEC_BITMAP
     *
     * @return the value of GTW_ATM_ISO_MSG_DEF.REQUEST_SEC_BITMAP
     */
    public String getREQUEST_SEC_BITMAP() {
        return REQUEST_SEC_BITMAP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ISO_MSG_DEF.REQUEST_SEC_BITMAP
     *
     * @param REQUEST_SEC_BITMAP the value for GTW_ATM_ISO_MSG_DEF.REQUEST_SEC_BITMAP
     */
    public void setREQUEST_SEC_BITMAP(String REQUEST_SEC_BITMAP) {
        this.REQUEST_SEC_BITMAP = REQUEST_SEC_BITMAP == null ? null : REQUEST_SEC_BITMAP.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ISO_MSG_DEF.RESPONSE_PRI_BITMAP
     *
     * @return the value of GTW_ATM_ISO_MSG_DEF.RESPONSE_PRI_BITMAP
     */
    public String getRESPONSE_PRI_BITMAP() {
        return RESPONSE_PRI_BITMAP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ISO_MSG_DEF.RESPONSE_PRI_BITMAP
     *
     * @param RESPONSE_PRI_BITMAP the value for GTW_ATM_ISO_MSG_DEF.RESPONSE_PRI_BITMAP
     */
    public void setRESPONSE_PRI_BITMAP(String RESPONSE_PRI_BITMAP) {
        this.RESPONSE_PRI_BITMAP = RESPONSE_PRI_BITMAP == null ? null : RESPONSE_PRI_BITMAP.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ISO_MSG_DEF.RESPONSE_SEC_BITMAP
     *
     * @return the value of GTW_ATM_ISO_MSG_DEF.RESPONSE_SEC_BITMAP
     */
    public String getRESPONSE_SEC_BITMAP() {
        return RESPONSE_SEC_BITMAP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ISO_MSG_DEF.RESPONSE_SEC_BITMAP
     *
     * @param RESPONSE_SEC_BITMAP the value for GTW_ATM_ISO_MSG_DEF.RESPONSE_SEC_BITMAP
     */
    public void setRESPONSE_SEC_BITMAP(String RESPONSE_SEC_BITMAP) {
        this.RESPONSE_SEC_BITMAP = RESPONSE_SEC_BITMAP == null ? null : RESPONSE_SEC_BITMAP.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ISO_MSG_DEF.CREATED_BY
     *
     * @return the value of GTW_ATM_ISO_MSG_DEF.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ISO_MSG_DEF.CREATED_BY
     *
     * @param CREATED_BY the value for GTW_ATM_ISO_MSG_DEF.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ISO_MSG_DEF.CREATED_DATE
     *
     * @return the value of GTW_ATM_ISO_MSG_DEF.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ISO_MSG_DEF.CREATED_DATE
     *
     * @param CREATED_DATE the value for GTW_ATM_ISO_MSG_DEF.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ISO_MSG_DEF.MODIFIED_BY
     *
     * @return the value of GTW_ATM_ISO_MSG_DEF.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ISO_MSG_DEF.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for GTW_ATM_ISO_MSG_DEF.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ISO_MSG_DEF.MODIFIED_DATE
     *
     * @return the value of GTW_ATM_ISO_MSG_DEF.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ISO_MSG_DEF.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for GTW_ATM_ISO_MSG_DEF.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }
}