package com.path.atm.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class GTW_ATM_INT_ISO_FLDSVO extends BaseVO {
    /**
     * This field corresponds to the database column GTW_ATM_INT_ISO_FLDS.ATM_ISO_FLDS_CODE
     */
    private BigDecimal ATM_ISO_FLDS_CODE;

    /**
     * This field corresponds to the database column GTW_ATM_INT_ISO_FLDS.INTERFACE_CODE
     */
    private BigDecimal INTERFACE_CODE;

    /**
     * This field corresponds to the database column GTW_ATM_INT_ISO_FLDS.FIELD_NO
     */
    private BigDecimal FIELD_CODE;

    /**
     * This field corresponds to the database column GTW_ATM_INT_ISO_FLDS.FIELD_NAME
     */
    private String FIELD_NAME;

    /**
     * This field corresponds to the database column GTW_ATM_INT_ISO_FLDS.FIELD_TYPE
     */
    private String FIELD_TYPE;

    /**
     * This field corresponds to the database column GTW_ATM_INT_ISO_FLDS.FIXED_LENGTH
     */
    private BigDecimal FIXED_LENGTH;

    /**
     * This field corresponds to the database column GTW_ATM_INT_ISO_FLDS.DYNAMIC_LENGTH
     */
    private BigDecimal DYNAMIC_LENGTH;

    /**
     * This field corresponds to the database column GTW_ATM_INT_ISO_FLDS.TOTAL_MASK_YN
     */
    private String TOTAL_MASK_YN;

    /**
     * This field corresponds to the database column GTW_ATM_INT_ISO_FLDS.PARTIAL_MASK
     */
    private String PARTIAL_MASK;

    /**
     * This field corresponds to the database column GTW_ATM_INT_ISO_FLDS.IS_DECIMAL_YN
     */
    private String IS_DECIMAL_YN;

    /**
     * This field corresponds to the database column GTW_ATM_INT_ISO_FLDS.EXPRESSION
     */
    private String EXPRESSION;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INT_ISO_FLDS.ATM_ISO_FLDS_CODE
     *
     * @return the value of GTW_ATM_INT_ISO_FLDS.ATM_ISO_FLDS_CODE
     */
    public BigDecimal getATM_ISO_FLDS_CODE() {
        return ATM_ISO_FLDS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INT_ISO_FLDS.ATM_ISO_FLDS_CODE
     *
     * @param ATM_ISO_FLDS_CODE the value for GTW_ATM_INT_ISO_FLDS.ATM_ISO_FLDS_CODE
     */
    public void setATM_ISO_FLDS_CODE(BigDecimal ATM_ISO_FLDS_CODE) {
        this.ATM_ISO_FLDS_CODE = ATM_ISO_FLDS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INT_ISO_FLDS.INTERFACE_CODE
     *
     * @return the value of GTW_ATM_INT_ISO_FLDS.INTERFACE_CODE
     */
    public BigDecimal getINTERFACE_CODE() {
        return INTERFACE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INT_ISO_FLDS.INTERFACE_CODE
     *
     * @param INTERFACE_CODE the value for GTW_ATM_INT_ISO_FLDS.INTERFACE_CODE
     */
    public void setINTERFACE_CODE(BigDecimal INTERFACE_CODE) {
        this.INTERFACE_CODE = INTERFACE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INT_ISO_FLDS.FIELD_CODE
     *
     * @return the value of GTW_ATM_INT_ISO_FLDS.FIELD_CODE
     */
    public BigDecimal getFIELD_CODE() {
        return FIELD_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INT_ISO_FLDS.FIELD_CODE
     *
     * @param FIELD_CODE the value for GTW_ATM_INT_ISO_FLDS.FIELD_CODE
     */
    public void setFIELD_CODE(BigDecimal FIELD_CODE) {
        this.FIELD_CODE = FIELD_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INT_ISO_FLDS.FIELD_NAME
     *
     * @return the value of GTW_ATM_INT_ISO_FLDS.FIELD_NAME
     */
    public String getFIELD_NAME() {
        return FIELD_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INT_ISO_FLDS.FIELD_NAME
     *
     * @param FIELD_NAME the value for GTW_ATM_INT_ISO_FLDS.FIELD_NAME
     */
    public void setFIELD_NAME(String FIELD_NAME) {
        this.FIELD_NAME = FIELD_NAME == null ? null : FIELD_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INT_ISO_FLDS.FIELD_TYPE
     *
     * @return the value of GTW_ATM_INT_ISO_FLDS.FIELD_TYPE
     */
    public String getFIELD_TYPE() {
        return FIELD_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INT_ISO_FLDS.FIELD_TYPE
     *
     * @param FIELD_TYPE the value for GTW_ATM_INT_ISO_FLDS.FIELD_TYPE
     */
    public void setFIELD_TYPE(String FIELD_TYPE) {
        this.FIELD_TYPE = FIELD_TYPE == null ? null : FIELD_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INT_ISO_FLDS.FIXED_LENGTH
     *
     * @return the value of GTW_ATM_INT_ISO_FLDS.FIXED_LENGTH
     */
    public BigDecimal getFIXED_LENGTH() {
        return FIXED_LENGTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INT_ISO_FLDS.FIXED_LENGTH
     *
     * @param FIXED_LENGTH the value for GTW_ATM_INT_ISO_FLDS.FIXED_LENGTH
     */
    public void setFIXED_LENGTH(BigDecimal FIXED_LENGTH) {
        this.FIXED_LENGTH = FIXED_LENGTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INT_ISO_FLDS.DYNAMIC_LENGTH
     *
     * @return the value of GTW_ATM_INT_ISO_FLDS.DYNAMIC_LENGTH
     */
    public BigDecimal getDYNAMIC_LENGTH() {
        return DYNAMIC_LENGTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INT_ISO_FLDS.DYNAMIC_LENGTH
     *
     * @param DYNAMIC_LENGTH the value for GTW_ATM_INT_ISO_FLDS.DYNAMIC_LENGTH
     */
    public void setDYNAMIC_LENGTH(BigDecimal DYNAMIC_LENGTH) {
        this.DYNAMIC_LENGTH = DYNAMIC_LENGTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INT_ISO_FLDS.TOTAL_MASK_YN
     *
     * @return the value of GTW_ATM_INT_ISO_FLDS.TOTAL_MASK_YN
     */
    public String getTOTAL_MASK_YN() {
        return TOTAL_MASK_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INT_ISO_FLDS.TOTAL_MASK_YN
     *
     * @param TOTAL_MASK_YN the value for GTW_ATM_INT_ISO_FLDS.TOTAL_MASK_YN
     */
    public void setTOTAL_MASK_YN(String TOTAL_MASK_YN) {
        this.TOTAL_MASK_YN = TOTAL_MASK_YN == null ? null : TOTAL_MASK_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INT_ISO_FLDS.PARTIAL_MASK
     *
     * @return the value of GTW_ATM_INT_ISO_FLDS.PARTIAL_MASK
     */
    public String getPARTIAL_MASK() {
        return PARTIAL_MASK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INT_ISO_FLDS.PARTIAL_MASK
     *
     * @param PARTIAL_MASK the value for GTW_ATM_INT_ISO_FLDS.PARTIAL_MASK
     */
    public void setPARTIAL_MASK(String PARTIAL_MASK) {
        this.PARTIAL_MASK = PARTIAL_MASK == null ? null : PARTIAL_MASK.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INT_ISO_FLDS.IS_DECIMAL_YN
     *
     * @return the value of GTW_ATM_INT_ISO_FLDS.IS_DECIMAL_YN
     */
    public String getIS_DECIMAL_YN() {
        return IS_DECIMAL_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INT_ISO_FLDS.IS_DECIMAL_YN
     *
     * @param IS_DECIMAL_YN the value for GTW_ATM_INT_ISO_FLDS.IS_DECIMAL_YN
     */
    public void setIS_DECIMAL_YN(String IS_DECIMAL_YN) {
        this.IS_DECIMAL_YN = IS_DECIMAL_YN == null ? null : IS_DECIMAL_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INT_ISO_FLDS.EXPRESSION
     *
     * @return the value of GTW_ATM_INT_ISO_FLDS.EXPRESSION
     */
    public String getEXPRESSION() {
        return EXPRESSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INT_ISO_FLDS.EXPRESSION
     *
     * @param EXPRESSION the value for GTW_ATM_INT_ISO_FLDS.EXPRESSION
     */
    public void setEXPRESSION(String EXPRESSION) {
        this.EXPRESSION = EXPRESSION == null ? null : EXPRESSION.trim();
    }
}