package com.path.atm.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class GTW_ATM_INT_ISO_SUB_FLDSVO extends BaseVO {
    /**
     * This field corresponds to the database column GTW_ATM_INT_ISO_SUB_FLDS.ATM_ISO_SUB_FLDS_CODE
     */
    private BigDecimal ATM_ISO_SUB_FLDS_CODE;

    /**
     * This field corresponds to the database column GTW_ATM_INT_ISO_SUB_FLDS.INTERFACE_CODE
     */
    private BigDecimal INTERFACE_CODE;

    /**
     * This field corresponds to the database column GTW_ATM_INT_ISO_SUB_FLDS.ATM_ISO_FLDS_CODE
     */
    private BigDecimal ATM_ISO_FLDS_CODE;

    /**
     * This field corresponds to the database column GTW_ATM_INT_ISO_SUB_FLDS.SUB_FIELD_CODE
     */
    private BigDecimal SUB_FIELD_CODE;

    /**
     * This field corresponds to the database column GTW_ATM_INT_ISO_SUB_FLDS.SUB_FIELD_NAME
     */
    private String SUB_FIELD_NAME;

    /**
     * This field corresponds to the database column GTW_ATM_INT_ISO_SUB_FLDS.SUB_FIELD_TYPE
     */
    private String SUB_FIELD_TYPE;

    /**
     * This field corresponds to the database column GTW_ATM_INT_ISO_SUB_FLDS.FIXED_LENGTH
     */
    private BigDecimal FIXED_LENGTH;

    /**
     * This field corresponds to the database column GTW_ATM_INT_ISO_SUB_FLDS.DYNAMIC_LENGTH
     */
    private BigDecimal DYNAMIC_LENGTH;

    /**
     * This field corresponds to the database column GTW_ATM_INT_ISO_SUB_FLDS.EXPRESSION
     */
    private String EXPRESSION;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INT_ISO_SUB_FLDS.ATM_ISO_SUB_FLDS_CODE
     *
     * @return the value of GTW_ATM_INT_ISO_SUB_FLDS.ATM_ISO_SUB_FLDS_CODE
     */
    public BigDecimal getATM_ISO_SUB_FLDS_CODE() {
        return ATM_ISO_SUB_FLDS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INT_ISO_SUB_FLDS.ATM_ISO_SUB_FLDS_CODE
     *
     * @param ATM_ISO_SUB_FLDS_CODE the value for GTW_ATM_INT_ISO_SUB_FLDS.ATM_ISO_SUB_FLDS_CODE
     */
    public void setATM_ISO_SUB_FLDS_CODE(BigDecimal ATM_ISO_SUB_FLDS_CODE) {
        this.ATM_ISO_SUB_FLDS_CODE = ATM_ISO_SUB_FLDS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INT_ISO_SUB_FLDS.INTERFACE_CODE
     *
     * @return the value of GTW_ATM_INT_ISO_SUB_FLDS.INTERFACE_CODE
     */
    public BigDecimal getINTERFACE_CODE() {
        return INTERFACE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INT_ISO_SUB_FLDS.INTERFACE_CODE
     *
     * @param INTERFACE_CODE the value for GTW_ATM_INT_ISO_SUB_FLDS.INTERFACE_CODE
     */
    public void setINTERFACE_CODE(BigDecimal INTERFACE_CODE) {
        this.INTERFACE_CODE = INTERFACE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INT_ISO_SUB_FLDS.ATM_ISO_FLDS_CODE
     *
     * @return the value of GTW_ATM_INT_ISO_SUB_FLDS.ATM_ISO_FLDS_CODE
     */
    public BigDecimal getATM_ISO_FLDS_CODE() {
        return ATM_ISO_FLDS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INT_ISO_SUB_FLDS.ATM_ISO_FLDS_CODE
     *
     * @param ATM_ISO_FLDS_CODE the value for GTW_ATM_INT_ISO_SUB_FLDS.ATM_ISO_FLDS_CODE
     */
    public void setATM_ISO_FLDS_CODE(BigDecimal ATM_ISO_FLDS_CODE) {
        this.ATM_ISO_FLDS_CODE = ATM_ISO_FLDS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INT_ISO_SUB_FLDS.SUB_FIELD_CODE
     *
     * @return the value of GTW_ATM_INT_ISO_SUB_FLDS.SUB_FIELD_CODE
     */
    public BigDecimal getSUB_FIELD_CODE() {
        return SUB_FIELD_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INT_ISO_SUB_FLDS.SUB_FIELD_CODE
     *
     * @param SUB_FIELD_CODE the value for GTW_ATM_INT_ISO_SUB_FLDS.SUB_FIELD_CODE
     */
    public void setSUB_FIELD_CODE(BigDecimal SUB_FIELD_CODE) {
        this.SUB_FIELD_CODE = SUB_FIELD_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INT_ISO_SUB_FLDS.SUB_FIELD_NAME
     *
     * @return the value of GTW_ATM_INT_ISO_SUB_FLDS.SUB_FIELD_NAME
     */
    public String getSUB_FIELD_NAME() {
        return SUB_FIELD_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INT_ISO_SUB_FLDS.SUB_FIELD_NAME
     *
     * @param SUB_FIELD_NAME the value for GTW_ATM_INT_ISO_SUB_FLDS.SUB_FIELD_NAME
     */
    public void setSUB_FIELD_NAME(String SUB_FIELD_NAME) {
        this.SUB_FIELD_NAME = SUB_FIELD_NAME == null ? null : SUB_FIELD_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INT_ISO_SUB_FLDS.SUB_FIELD_TYPE
     *
     * @return the value of GTW_ATM_INT_ISO_SUB_FLDS.SUB_FIELD_TYPE
     */
    public String getSUB_FIELD_TYPE() {
        return SUB_FIELD_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INT_ISO_SUB_FLDS.SUB_FIELD_TYPE
     *
     * @param SUB_FIELD_TYPE the value for GTW_ATM_INT_ISO_SUB_FLDS.SUB_FIELD_TYPE
     */
    public void setSUB_FIELD_TYPE(String SUB_FIELD_TYPE) {
        this.SUB_FIELD_TYPE = SUB_FIELD_TYPE == null ? null : SUB_FIELD_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INT_ISO_SUB_FLDS.FIXED_LENGTH
     *
     * @return the value of GTW_ATM_INT_ISO_SUB_FLDS.FIXED_LENGTH
     */
    public BigDecimal getFIXED_LENGTH() {
        return FIXED_LENGTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INT_ISO_SUB_FLDS.FIXED_LENGTH
     *
     * @param FIXED_LENGTH the value for GTW_ATM_INT_ISO_SUB_FLDS.FIXED_LENGTH
     */
    public void setFIXED_LENGTH(BigDecimal FIXED_LENGTH) {
        this.FIXED_LENGTH = FIXED_LENGTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INT_ISO_SUB_FLDS.DYNAMIC_LENGTH
     *
     * @return the value of GTW_ATM_INT_ISO_SUB_FLDS.DYNAMIC_LENGTH
     */
    public BigDecimal getDYNAMIC_LENGTH() {
        return DYNAMIC_LENGTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INT_ISO_SUB_FLDS.DYNAMIC_LENGTH
     *
     * @param DYNAMIC_LENGTH the value for GTW_ATM_INT_ISO_SUB_FLDS.DYNAMIC_LENGTH
     */
    public void setDYNAMIC_LENGTH(BigDecimal DYNAMIC_LENGTH) {
        this.DYNAMIC_LENGTH = DYNAMIC_LENGTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INT_ISO_SUB_FLDS.EXPRESSION
     *
     * @return the value of GTW_ATM_INT_ISO_SUB_FLDS.EXPRESSION
     */
    public String getEXPRESSION() {
        return EXPRESSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INT_ISO_SUB_FLDS.EXPRESSION
     *
     * @param EXPRESSION the value for GTW_ATM_INT_ISO_SUB_FLDS.EXPRESSION
     */
    public void setEXPRESSION(String EXPRESSION) {
        this.EXPRESSION = EXPRESSION == null ? null : EXPRESSION.trim();
    }
}