package com.path.atm.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class GTW_ATM_ACQUIRERVO extends BaseVO {
    /**
     * This field corresponds to the database column GTW_ATM_ACQUIRER.ACQUIRER_ID
     */
    private BigDecimal ACQUIRER_ID;

    /**
     * This field corresponds to the database column GTW_ATM_ACQUIRER.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column GTW_ATM_ACQUIRER.DESCRIPTION
     */
    private String DESCRIPTION;

    /**
     * This field corresponds to the database column GTW_ATM_ACQUIRER.INTERFACE_CODE
     */
    private BigDecimal INTERFACE_CODE;

    /**
     * This field corresponds to the database column GTW_ATM_ACQUIRER.ACQUIRER_MSG_SOURCE
     */
    private String ACQUIRER_MSG_SOURCE;

    /**
     * This field corresponds to the database column GTW_ATM_ACQUIRER.BANK_ATM_YN
     */
    private String BANK_ATM_YN;

    /**
     * This field corresponds to the database column GTW_ATM_ACQUIRER.TRANSACTION_BRANCH_CODE
     */
    private BigDecimal TRANSACTION_BRANCH_CODE;

    /**
     * This field corresponds to the database column GTW_ATM_ACQUIRER.TELLER_CODE
     */
    private BigDecimal TELLER_CODE;

    /**
     * This field corresponds to the database column GTW_ATM_ACQUIRER.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column GTW_ATM_ACQUIRER.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column GTW_ATM_ACQUIRER.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column GTW_ATM_ACQUIRER.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This field corresponds to the database column GTW_ATM_ACQUIRER.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column GTW_ATM_ACQUIRER.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This field corresponds to the database column GTW_ATM_ACQUIRER.DELETED_DATE
     */
    private Date DELETED_DATE;

    /**
     * This field corresponds to the database column GTW_ATM_ACQUIRER.TELLER_USER_ID
     */
    private String TELLER_USER_ID;

    /**
     * This field corresponds to the database column GTW_ATM_ACQUIRER.TERMINAL_TYPE
     */
    private String TERMINAL_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ACQUIRER.ACQUIRER_ID
     *
     * @return the value of GTW_ATM_ACQUIRER.ACQUIRER_ID
     */
    public BigDecimal getACQUIRER_ID() {
        return ACQUIRER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ACQUIRER.ACQUIRER_ID
     *
     * @param ACQUIRER_ID the value for GTW_ATM_ACQUIRER.ACQUIRER_ID
     */
    public void setACQUIRER_ID(BigDecimal ACQUIRER_ID) {
        this.ACQUIRER_ID = ACQUIRER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ACQUIRER.COMP_CODE
     *
     * @return the value of GTW_ATM_ACQUIRER.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ACQUIRER.COMP_CODE
     *
     * @param COMP_CODE the value for GTW_ATM_ACQUIRER.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ACQUIRER.DESCRIPTION
     *
     * @return the value of GTW_ATM_ACQUIRER.DESCRIPTION
     */
    public String getDESCRIPTION() {
        return DESCRIPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ACQUIRER.DESCRIPTION
     *
     * @param DESCRIPTION the value for GTW_ATM_ACQUIRER.DESCRIPTION
     */
    public void setDESCRIPTION(String DESCRIPTION) {
        this.DESCRIPTION = DESCRIPTION == null ? null : DESCRIPTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ACQUIRER.INTERFACE_CODE
     *
     * @return the value of GTW_ATM_ACQUIRER.INTERFACE_CODE
     */
    public BigDecimal getINTERFACE_CODE() {
        return INTERFACE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ACQUIRER.INTERFACE_CODE
     *
     * @param INTERFACE_CODE the value for GTW_ATM_ACQUIRER.INTERFACE_CODE
     */
    public void setINTERFACE_CODE(BigDecimal INTERFACE_CODE) {
        this.INTERFACE_CODE = INTERFACE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ACQUIRER.ACQUIRER_MSG_SOURCE
     *
     * @return the value of GTW_ATM_ACQUIRER.ACQUIRER_MSG_SOURCE
     */
    public String getACQUIRER_MSG_SOURCE() {
        return ACQUIRER_MSG_SOURCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ACQUIRER.ACQUIRER_MSG_SOURCE
     *
     * @param ACQUIRER_MSG_SOURCE the value for GTW_ATM_ACQUIRER.ACQUIRER_MSG_SOURCE
     */
    public void setACQUIRER_MSG_SOURCE(String ACQUIRER_MSG_SOURCE) {
        this.ACQUIRER_MSG_SOURCE = ACQUIRER_MSG_SOURCE == null ? null : ACQUIRER_MSG_SOURCE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ACQUIRER.BANK_ATM_YN
     *
     * @return the value of GTW_ATM_ACQUIRER.BANK_ATM_YN
     */
    public String getBANK_ATM_YN() {
        return BANK_ATM_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ACQUIRER.BANK_ATM_YN
     *
     * @param BANK_ATM_YN the value for GTW_ATM_ACQUIRER.BANK_ATM_YN
     */
    public void setBANK_ATM_YN(String BANK_ATM_YN) {
        this.BANK_ATM_YN = BANK_ATM_YN == null ? null : BANK_ATM_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ACQUIRER.TRANSACTION_BRANCH_CODE
     *
     * @return the value of GTW_ATM_ACQUIRER.TRANSACTION_BRANCH_CODE
     */
    public BigDecimal getTRANSACTION_BRANCH_CODE() {
        return TRANSACTION_BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ACQUIRER.TRANSACTION_BRANCH_CODE
     *
     * @param TRANSACTION_BRANCH_CODE the value for GTW_ATM_ACQUIRER.TRANSACTION_BRANCH_CODE
     */
    public void setTRANSACTION_BRANCH_CODE(BigDecimal TRANSACTION_BRANCH_CODE) {
        this.TRANSACTION_BRANCH_CODE = TRANSACTION_BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ACQUIRER.TELLER_CODE
     *
     * @return the value of GTW_ATM_ACQUIRER.TELLER_CODE
     */
    public BigDecimal getTELLER_CODE() {
        return TELLER_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ACQUIRER.TELLER_CODE
     *
     * @param TELLER_CODE the value for GTW_ATM_ACQUIRER.TELLER_CODE
     */
    public void setTELLER_CODE(BigDecimal TELLER_CODE) {
        this.TELLER_CODE = TELLER_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ACQUIRER.CREATED_BY
     *
     * @return the value of GTW_ATM_ACQUIRER.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ACQUIRER.CREATED_BY
     *
     * @param CREATED_BY the value for GTW_ATM_ACQUIRER.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ACQUIRER.CREATED_DATE
     *
     * @return the value of GTW_ATM_ACQUIRER.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ACQUIRER.CREATED_DATE
     *
     * @param CREATED_DATE the value for GTW_ATM_ACQUIRER.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ACQUIRER.MODIFIED_BY
     *
     * @return the value of GTW_ATM_ACQUIRER.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ACQUIRER.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for GTW_ATM_ACQUIRER.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ACQUIRER.DATE_UPDATED
     *
     * @return the value of GTW_ATM_ACQUIRER.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ACQUIRER.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for GTW_ATM_ACQUIRER.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ACQUIRER.MODIFIED_DATE
     *
     * @return the value of GTW_ATM_ACQUIRER.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ACQUIRER.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for GTW_ATM_ACQUIRER.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ACQUIRER.DELETED_BY
     *
     * @return the value of GTW_ATM_ACQUIRER.DELETED_BY
     */
    public String getDELETED_BY() {
        return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ACQUIRER.DELETED_BY
     *
     * @param DELETED_BY the value for GTW_ATM_ACQUIRER.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY) {
        this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ACQUIRER.DELETED_DATE
     *
     * @return the value of GTW_ATM_ACQUIRER.DELETED_DATE
     */
    public Date getDELETED_DATE() {
        return DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ACQUIRER.DELETED_DATE
     *
     * @param DELETED_DATE the value for GTW_ATM_ACQUIRER.DELETED_DATE
     */
    public void setDELETED_DATE(Date DELETED_DATE) {
        this.DELETED_DATE = DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ACQUIRER.TELLER_USER_ID
     *
     * @return the value of GTW_ATM_ACQUIRER.TELLER_USER_ID
     */
    public String getTELLER_USER_ID() {
        return TELLER_USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ACQUIRER.TELLER_USER_ID
     *
     * @param TELLER_USER_ID the value for GTW_ATM_ACQUIRER.TELLER_USER_ID
     */
    public void setTELLER_USER_ID(String TELLER_USER_ID) {
        this.TELLER_USER_ID = TELLER_USER_ID == null ? null : TELLER_USER_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_ACQUIRER.TERMINAL_TYPE
     *
     * @return the value of GTW_ATM_ACQUIRER.TERMINAL_TYPE
     */
    public String getTERMINAL_TYPE() {
        return TERMINAL_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_ACQUIRER.TERMINAL_TYPE
     *
     * @param TERMINAL_TYPE the value for GTW_ATM_ACQUIRER.TERMINAL_TYPE
     */
    public void setTERMINAL_TYPE(String TERMINAL_TYPE) {
        this.TERMINAL_TYPE = TERMINAL_TYPE == null ? null : TERMINAL_TYPE.trim();
    }
}