package com.path.atm.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class GTW_ATM_INTERFACESVO extends BaseVO {
    /**
     * This field corresponds to the database column GTW_ATM_INTERFACES.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column GTW_ATM_INTERFACES.INTERFACE_CODE
     */
    private BigDecimal INTERFACE_CODE;

    /**
     * This field corresponds to the database column GTW_ATM_INTERFACES.DESCRIPTION
     */
    private String DESCRIPTION;

    /**
     * This field corresponds to the database column GTW_ATM_INTERFACES.INTERFACE_TYPE
     */
    private String INTERFACE_TYPE;

    /**
     * This field corresponds to the database column GTW_ATM_INTERFACES.INCLUDE_LENGTH
     */
    private BigDecimal INCLUDE_LENGTH;

    /**
     * This field corresponds to the database column GTW_ATM_INTERFACES.MSG_LENGTH
     */
    private BigDecimal MSG_LENGTH;

    /**
     * This field corresponds to the database column GTW_ATM_INTERFACES.HEADER_LENGTH
     */
    private BigDecimal HEADER_LENGTH;

    /**
     * This field corresponds to the database column GTW_ATM_INTERFACES.HEADER_DATA
     */
    private String HEADER_DATA;

    /**
     * This field corresponds to the database column GTW_ATM_INTERFACES.BITMAP_TYPE
     */
    private String BITMAP_TYPE;

    /**
     * This field corresponds to the database column GTW_ATM_INTERFACES.LENGTH_TYPE
     */
    private String LENGTH_TYPE;

    /**
     * This field corresponds to the database column GTW_ATM_INTERFACES.CURRENT_DATE
     */
    private Date CURRENT_DATE;

    /**
     * This field corresponds to the database column GTW_ATM_INTERFACES.INCLUDE_HEADER_YN
     */
    private String INCLUDE_HEADER_YN;

    /**
     * This field corresponds to the database column GTW_ATM_INTERFACES.POS_IN_HEADER_YN
     */
    private String POS_IN_HEADER_YN;

    /**
     * This field corresponds to the database column GTW_ATM_INTERFACES.ISO_PRESENT_YN
     */
    private String ISO_PRESENT_YN;

    /**
     * This field corresponds to the database column GTW_ATM_INTERFACES.SKIP_BITMAP_YN
     */
    private String SKIP_BITMAP_YN;

    /**
     * This field corresponds to the database column GTW_ATM_INTERFACES.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column GTW_ATM_INTERFACES.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column GTW_ATM_INTERFACES.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column GTW_ATM_INTERFACES.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column GTW_ATM_INTERFACES.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column GTW_ATM_INTERFACES.APPROVED_BY
     */
    private String APPROVED_BY;

    /**
     * This field corresponds to the database column GTW_ATM_INTERFACES.APPROVED_DATE
     */
    private Date APPROVED_DATE;

    /**
     * This field corresponds to the database column GTW_ATM_INTERFACES.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This field corresponds to the database column GTW_ATM_INTERFACES.DELETED_DATE
     */
    private Date DELETED_DATE;

    /**
     * This field corresponds to the database column GTW_ATM_INTERFACES.SUSPENDED_BY
     */
    private String SUSPENDED_BY;

    /**
     * This field corresponds to the database column GTW_ATM_INTERFACES.SUSPENDED_DATE
     */
    private Date SUSPENDED_DATE;

    /**
     * This field corresponds to the database column GTW_ATM_INTERFACES.REACTIVATED_BY
     */
    private String REACTIVATED_BY;

    /**
     * This field corresponds to the database column GTW_ATM_INTERFACES.REACTIVATED_DATE
     */
    private Date REACTIVATED_DATE;
    
    /**
     * This field corresponds to the database column GTW_ATM_INTERFACES.PROTOCOL_IDENTITFICATION
     */
    private String PROTOCOL_IDENTITFICATION;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INTERFACES.COMP_CODE
     *
     * @return the value of GTW_ATM_INTERFACES.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INTERFACES.COMP_CODE
     *
     * @param COMP_CODE the value for GTW_ATM_INTERFACES.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INTERFACES.INTERFACE_CODE
     *
     * @return the value of GTW_ATM_INTERFACES.INTERFACE_CODE
     */
    public BigDecimal getINTERFACE_CODE() {
        return INTERFACE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INTERFACES.INTERFACE_CODE
     *
     * @param INTERFACE_CODE the value for GTW_ATM_INTERFACES.INTERFACE_CODE
     */
    public void setINTERFACE_CODE(BigDecimal INTERFACE_CODE) {
        this.INTERFACE_CODE = INTERFACE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INTERFACES.DESCRIPTION
     *
     * @return the value of GTW_ATM_INTERFACES.DESCRIPTION
     */
    public String getDESCRIPTION() {
        return DESCRIPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INTERFACES.DESCRIPTION
     *
     * @param DESCRIPTION the value for GTW_ATM_INTERFACES.DESCRIPTION
     */
    public void setDESCRIPTION(String DESCRIPTION) {
        this.DESCRIPTION = DESCRIPTION == null ? null : DESCRIPTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INTERFACES.INTERFACE_TYPE
     *
     * @return the value of GTW_ATM_INTERFACES.INTERFACE_TYPE
     */
    public String getINTERFACE_TYPE() {
        return INTERFACE_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INTERFACES.INTERFACE_TYPE
     *
     * @param INTERFACE_TYPE the value for GTW_ATM_INTERFACES.INTERFACE_TYPE
     */
    public void setINTERFACE_TYPE(String INTERFACE_TYPE) {
        this.INTERFACE_TYPE = INTERFACE_TYPE == null ? null : INTERFACE_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INTERFACES.INCLUDE_LENGTH
     *
     * @return the value of GTW_ATM_INTERFACES.INCLUDE_LENGTH
     */
    public BigDecimal getINCLUDE_LENGTH() {
        return INCLUDE_LENGTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INTERFACES.INCLUDE_LENGTH
     *
     * @param INCLUDE_LENGTH the value for GTW_ATM_INTERFACES.INCLUDE_LENGTH
     */
    public void setINCLUDE_LENGTH(BigDecimal INCLUDE_LENGTH) {
        this.INCLUDE_LENGTH = INCLUDE_LENGTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INTERFACES.MSG_LENGTH
     *
     * @return the value of GTW_ATM_INTERFACES.MSG_LENGTH
     */
    public BigDecimal getMSG_LENGTH() {
        return MSG_LENGTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INTERFACES.MSG_LENGTH
     *
     * @param MSG_LENGTH the value for GTW_ATM_INTERFACES.MSG_LENGTH
     */
    public void setMSG_LENGTH(BigDecimal MSG_LENGTH) {
        this.MSG_LENGTH = MSG_LENGTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INTERFACES.HEADER_LENGTH
     *
     * @return the value of GTW_ATM_INTERFACES.HEADER_LENGTH
     */
    public BigDecimal getHEADER_LENGTH() {
        return HEADER_LENGTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INTERFACES.HEADER_LENGTH
     *
     * @param HEADER_LENGTH the value for GTW_ATM_INTERFACES.HEADER_LENGTH
     */
    public void setHEADER_LENGTH(BigDecimal HEADER_LENGTH) {
        this.HEADER_LENGTH = HEADER_LENGTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INTERFACES.HEADER_DATA
     *
     * @return the value of GTW_ATM_INTERFACES.HEADER_DATA
     */
    public String getHEADER_DATA() {
        return HEADER_DATA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INTERFACES.HEADER_DATA
     *
     * @param HEADER_DATA the value for GTW_ATM_INTERFACES.HEADER_DATA
     */
    public void setHEADER_DATA(String HEADER_DATA) {
        this.HEADER_DATA = HEADER_DATA == null ? null : HEADER_DATA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INTERFACES.BITMAP_TYPE
     *
     * @return the value of GTW_ATM_INTERFACES.BITMAP_TYPE
     */
    public String getBITMAP_TYPE() {
        return BITMAP_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INTERFACES.BITMAP_TYPE
     *
     * @param BITMAP_TYPE the value for GTW_ATM_INTERFACES.BITMAP_TYPE
     */
    public void setBITMAP_TYPE(String BITMAP_TYPE) {
        this.BITMAP_TYPE = BITMAP_TYPE == null ? null : BITMAP_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INTERFACES.LENGTH_TYPE
     *
     * @return the value of GTW_ATM_INTERFACES.LENGTH_TYPE
     */
    public String getLENGTH_TYPE() {
        return LENGTH_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INTERFACES.LENGTH_TYPE
     *
     * @param LENGTH_TYPE the value for GTW_ATM_INTERFACES.LENGTH_TYPE
     */
    public void setLENGTH_TYPE(String LENGTH_TYPE) {
        this.LENGTH_TYPE = LENGTH_TYPE == null ? null : LENGTH_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INTERFACES.CURRENT_DATE
     *
     * @return the value of GTW_ATM_INTERFACES.CURRENT_DATE
     */
    public Date getCURRENT_DATE() {
        return CURRENT_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INTERFACES.CURRENT_DATE
     *
     * @param CURRENT_DATE the value for GTW_ATM_INTERFACES.CURRENT_DATE
     */
    public void setCURRENT_DATE(Date CURRENT_DATE) {
        this.CURRENT_DATE = CURRENT_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INTERFACES.INCLUDE_HEADER_YN
     *
     * @return the value of GTW_ATM_INTERFACES.INCLUDE_HEADER_YN
     */
    public String getINCLUDE_HEADER_YN() {
        return INCLUDE_HEADER_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INTERFACES.INCLUDE_HEADER_YN
     *
     * @param INCLUDE_HEADER_YN the value for GTW_ATM_INTERFACES.INCLUDE_HEADER_YN
     */
    public void setINCLUDE_HEADER_YN(String INCLUDE_HEADER_YN) {
        this.INCLUDE_HEADER_YN = INCLUDE_HEADER_YN == null ? null : INCLUDE_HEADER_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INTERFACES.POS_IN_HEADER_YN
     *
     * @return the value of GTW_ATM_INTERFACES.POS_IN_HEADER_YN
     */
    public String getPOS_IN_HEADER_YN() {
        return POS_IN_HEADER_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INTERFACES.POS_IN_HEADER_YN
     *
     * @param POS_IN_HEADER_YN the value for GTW_ATM_INTERFACES.POS_IN_HEADER_YN
     */
    public void setPOS_IN_HEADER_YN(String POS_IN_HEADER_YN) {
        this.POS_IN_HEADER_YN = POS_IN_HEADER_YN == null ? null : POS_IN_HEADER_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INTERFACES.ISO_PRESENT_YN
     *
     * @return the value of GTW_ATM_INTERFACES.ISO_PRESENT_YN
     */
    public String getISO_PRESENT_YN() {
        return ISO_PRESENT_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INTERFACES.ISO_PRESENT_YN
     *
     * @param ISO_PRESENT_YN the value for GTW_ATM_INTERFACES.ISO_PRESENT_YN
     */
    public void setISO_PRESENT_YN(String ISO_PRESENT_YN) {
        this.ISO_PRESENT_YN = ISO_PRESENT_YN == null ? null : ISO_PRESENT_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INTERFACES.SKIP_BITMAP_YN
     *
     * @return the value of GTW_ATM_INTERFACES.SKIP_BITMAP_YN
     */
    public String getSKIP_BITMAP_YN() {
        return SKIP_BITMAP_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INTERFACES.SKIP_BITMAP_YN
     *
     * @param SKIP_BITMAP_YN the value for GTW_ATM_INTERFACES.SKIP_BITMAP_YN
     */
    public void setSKIP_BITMAP_YN(String SKIP_BITMAP_YN) {
        this.SKIP_BITMAP_YN = SKIP_BITMAP_YN == null ? null : SKIP_BITMAP_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INTERFACES.STATUS
     *
     * @return the value of GTW_ATM_INTERFACES.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INTERFACES.STATUS
     *
     * @param STATUS the value for GTW_ATM_INTERFACES.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INTERFACES.CREATED_BY
     *
     * @return the value of GTW_ATM_INTERFACES.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INTERFACES.CREATED_BY
     *
     * @param CREATED_BY the value for GTW_ATM_INTERFACES.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INTERFACES.CREATED_DATE
     *
     * @return the value of GTW_ATM_INTERFACES.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INTERFACES.CREATED_DATE
     *
     * @param CREATED_DATE the value for GTW_ATM_INTERFACES.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INTERFACES.MODIFIED_BY
     *
     * @return the value of GTW_ATM_INTERFACES.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INTERFACES.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for GTW_ATM_INTERFACES.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INTERFACES.MODIFIED_DATE
     *
     * @return the value of GTW_ATM_INTERFACES.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INTERFACES.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for GTW_ATM_INTERFACES.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INTERFACES.APPROVED_BY
     *
     * @return the value of GTW_ATM_INTERFACES.APPROVED_BY
     */
    public String getAPPROVED_BY() {
        return APPROVED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INTERFACES.APPROVED_BY
     *
     * @param APPROVED_BY the value for GTW_ATM_INTERFACES.APPROVED_BY
     */
    public void setAPPROVED_BY(String APPROVED_BY) {
        this.APPROVED_BY = APPROVED_BY == null ? null : APPROVED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INTERFACES.APPROVED_DATE
     *
     * @return the value of GTW_ATM_INTERFACES.APPROVED_DATE
     */
    public Date getAPPROVED_DATE() {
        return APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INTERFACES.APPROVED_DATE
     *
     * @param APPROVED_DATE the value for GTW_ATM_INTERFACES.APPROVED_DATE
     */
    public void setAPPROVED_DATE(Date APPROVED_DATE) {
        this.APPROVED_DATE = APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INTERFACES.DELETED_BY
     *
     * @return the value of GTW_ATM_INTERFACES.DELETED_BY
     */
    public String getDELETED_BY() {
        return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INTERFACES.DELETED_BY
     *
     * @param DELETED_BY the value for GTW_ATM_INTERFACES.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY) {
        this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INTERFACES.DELETED_DATE
     *
     * @return the value of GTW_ATM_INTERFACES.DELETED_DATE
     */
    public Date getDELETED_DATE() {
        return DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INTERFACES.DELETED_DATE
     *
     * @param DELETED_DATE the value for GTW_ATM_INTERFACES.DELETED_DATE
     */
    public void setDELETED_DATE(Date DELETED_DATE) {
        this.DELETED_DATE = DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INTERFACES.SUSPENDED_BY
     *
     * @return the value of GTW_ATM_INTERFACES.SUSPENDED_BY
     */
    public String getSUSPENDED_BY() {
        return SUSPENDED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INTERFACES.SUSPENDED_BY
     *
     * @param SUSPENDED_BY the value for GTW_ATM_INTERFACES.SUSPENDED_BY
     */
    public void setSUSPENDED_BY(String SUSPENDED_BY) {
        this.SUSPENDED_BY = SUSPENDED_BY == null ? null : SUSPENDED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INTERFACES.SUSPENDED_DATE
     *
     * @return the value of GTW_ATM_INTERFACES.SUSPENDED_DATE
     */
    public Date getSUSPENDED_DATE() {
        return SUSPENDED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INTERFACES.SUSPENDED_DATE
     *
     * @param SUSPENDED_DATE the value for GTW_ATM_INTERFACES.SUSPENDED_DATE
     */
    public void setSUSPENDED_DATE(Date SUSPENDED_DATE) {
        this.SUSPENDED_DATE = SUSPENDED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INTERFACES.REACTIVATED_BY
     *
     * @return the value of GTW_ATM_INTERFACES.REACTIVATED_BY
     */
    public String getREACTIVATED_BY() {
        return REACTIVATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INTERFACES.REACTIVATED_BY
     *
     * @param REACTIVATED_BY the value for GTW_ATM_INTERFACES.REACTIVATED_BY
     */
    public void setREACTIVATED_BY(String REACTIVATED_BY) {
        this.REACTIVATED_BY = REACTIVATED_BY == null ? null : REACTIVATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INTERFACES.REACTIVATED_DATE
     *
     * @return the value of GTW_ATM_INTERFACES.REACTIVATED_DATE
     */
    public Date getREACTIVATED_DATE() {
        return REACTIVATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INTERFACES.REACTIVATED_DATE
     *
     * @param REACTIVATED_DATE the value for GTW_ATM_INTERFACES.REACTIVATED_DATE
     */
    public void setREACTIVATED_DATE(Date REACTIVATED_DATE) {
        this.REACTIVATED_DATE = REACTIVATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_INTERFACES.PROTOCOL_IDENTITFICATION
     *
     * @return the value of GTW_ATM_INTERFACES.PROTOCOL_IDENTITFICATION
     */
    public String getPROTOCOL_IDENTITFICATION()
    {
        return PROTOCOL_IDENTITFICATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_INTERFACES.PROTOCOL_IDENTITFICATION
     *
     * @param REACTIVATED_DATE the value for GTW_ATM_INTERFACES.PROTOCOL_IDENTITFICATION
     */
    public void setPROTOCOL_IDENTITFICATION(String PROTOCOL_IDENTITFICATION)
    {
        this.PROTOCOL_IDENTITFICATION = PROTOCOL_IDENTITFICATION;
    }
    
    
}