package com.path.atm.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class GTW_ATM_TERMINALVO extends BaseVO {
    /**
     * This field corresponds to the database column GTW_ATM_TERMINAL.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column GTW_ATM_TERMINAL.TERMINAL_ID
     */
    private BigDecimal TERMINAL_ID;

    /**
     * This field corresponds to the database column GTW_ATM_TERMINAL.DESCRIPTION
     */
    private String DESCRIPTION;

    /**
     * This field corresponds to the database column GTW_ATM_TERMINAL.MERCHANT_CODE
     */
    private BigDecimal MERCHANT_CODE;

    /**
     * This field corresponds to the database column GTW_ATM_TERMINAL.TRANSACTION_BRANCH_CODE
     */
    private BigDecimal TRANSACTION_BRANCH_CODE;

    /**
     * This field corresponds to the database column GTW_ATM_TERMINAL.TELLER_CODE
     */
    private BigDecimal TELLER_CODE;

    /**
     * This field corresponds to the database column GTW_ATM_TERMINAL.ADDRESS
     */
    private String ADDRESS;

    /**
     * This field corresponds to the database column GTW_ATM_TERMINAL.TELEPHONE
     */
    private String TELEPHONE;

    /**
     * This field corresponds to the database column GTW_ATM_TERMINAL.EMAIL
     */
    private String EMAIL;

    /**
     * This field corresponds to the database column GTW_ATM_TERMINAL.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This field corresponds to the database column GTW_ATM_TERMINAL.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column GTW_ATM_TERMINAL.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column GTW_ATM_TERMINAL.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column GTW_ATM_TERMINAL.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column GTW_ATM_TERMINAL.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This field corresponds to the database column GTW_ATM_TERMINAL.DELETED_DATE
     */
    private Date DELETED_DATE;

    /**
     * This field corresponds to the database column GTW_ATM_TERMINAL.TERMINAL_CODE
     */
    private String TERMINAL_CODE;

    /**
     * This field corresponds to the database column GTW_ATM_TERMINAL.INTERFACE_CODE
     */
    private BigDecimal INTERFACE_CODE;

    /**
     * This field corresponds to the database column GTW_ATM_TERMINAL.EXPRESSION
     */
    private String EXPRESSION;

    /**
     * This field corresponds to the database column GTW_ATM_TERMINAL.TELLER_USER_ID
     */
    private String TELLER_USER_ID;

    /**
     * This field corresponds to the database column GTW_ATM_TERMINAL.ACQUIRER_ID
     */
    private BigDecimal ACQUIRER_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_TERMINAL.COMP_CODE
     *
     * @return the value of GTW_ATM_TERMINAL.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_TERMINAL.COMP_CODE
     *
     * @param COMP_CODE the value for GTW_ATM_TERMINAL.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_TERMINAL.TERMINAL_ID
     *
     * @return the value of GTW_ATM_TERMINAL.TERMINAL_ID
     */
    public BigDecimal getTERMINAL_ID() {
        return TERMINAL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_TERMINAL.TERMINAL_ID
     *
     * @param TERMINAL_ID the value for GTW_ATM_TERMINAL.TERMINAL_ID
     */
    public void setTERMINAL_ID(BigDecimal TERMINAL_ID) {
        this.TERMINAL_ID = TERMINAL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_TERMINAL.DESCRIPTION
     *
     * @return the value of GTW_ATM_TERMINAL.DESCRIPTION
     */
    public String getDESCRIPTION() {
        return DESCRIPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_TERMINAL.DESCRIPTION
     *
     * @param DESCRIPTION the value for GTW_ATM_TERMINAL.DESCRIPTION
     */
    public void setDESCRIPTION(String DESCRIPTION) {
        this.DESCRIPTION = DESCRIPTION == null ? null : DESCRIPTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_TERMINAL.MERCHANT_CODE
     *
     * @return the value of GTW_ATM_TERMINAL.MERCHANT_CODE
     */
    public BigDecimal getMERCHANT_CODE() {
        return MERCHANT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_TERMINAL.MERCHANT_CODE
     *
     * @param MERCHANT_CODE the value for GTW_ATM_TERMINAL.MERCHANT_CODE
     */
    public void setMERCHANT_CODE(BigDecimal MERCHANT_CODE) {
        this.MERCHANT_CODE = MERCHANT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_TERMINAL.TRANSACTION_BRANCH_CODE
     *
     * @return the value of GTW_ATM_TERMINAL.TRANSACTION_BRANCH_CODE
     */
    public BigDecimal getTRANSACTION_BRANCH_CODE() {
        return TRANSACTION_BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_TERMINAL.TRANSACTION_BRANCH_CODE
     *
     * @param TRANSACTION_BRANCH_CODE the value for GTW_ATM_TERMINAL.TRANSACTION_BRANCH_CODE
     */
    public void setTRANSACTION_BRANCH_CODE(BigDecimal TRANSACTION_BRANCH_CODE) {
        this.TRANSACTION_BRANCH_CODE = TRANSACTION_BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_TERMINAL.TELLER_CODE
     *
     * @return the value of GTW_ATM_TERMINAL.TELLER_CODE
     */
    public BigDecimal getTELLER_CODE() {
        return TELLER_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_TERMINAL.TELLER_CODE
     *
     * @param TELLER_CODE the value for GTW_ATM_TERMINAL.TELLER_CODE
     */
    public void setTELLER_CODE(BigDecimal TELLER_CODE) {
        this.TELLER_CODE = TELLER_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_TERMINAL.ADDRESS
     *
     * @return the value of GTW_ATM_TERMINAL.ADDRESS
     */
    public String getADDRESS() {
        return ADDRESS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_TERMINAL.ADDRESS
     *
     * @param ADDRESS the value for GTW_ATM_TERMINAL.ADDRESS
     */
    public void setADDRESS(String ADDRESS) {
        this.ADDRESS = ADDRESS == null ? null : ADDRESS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_TERMINAL.TELEPHONE
     *
     * @return the value of GTW_ATM_TERMINAL.TELEPHONE
     */
    public String getTELEPHONE() {
        return TELEPHONE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_TERMINAL.TELEPHONE
     *
     * @param TELEPHONE the value for GTW_ATM_TERMINAL.TELEPHONE
     */
    public void setTELEPHONE(String TELEPHONE) {
        this.TELEPHONE = TELEPHONE == null ? null : TELEPHONE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_TERMINAL.EMAIL
     *
     * @return the value of GTW_ATM_TERMINAL.EMAIL
     */
    public String getEMAIL() {
        return EMAIL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_TERMINAL.EMAIL
     *
     * @param EMAIL the value for GTW_ATM_TERMINAL.EMAIL
     */
    public void setEMAIL(String EMAIL) {
        this.EMAIL = EMAIL == null ? null : EMAIL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_TERMINAL.DATE_UPDATED
     *
     * @return the value of GTW_ATM_TERMINAL.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_TERMINAL.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for GTW_ATM_TERMINAL.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_TERMINAL.CREATED_BY
     *
     * @return the value of GTW_ATM_TERMINAL.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_TERMINAL.CREATED_BY
     *
     * @param CREATED_BY the value for GTW_ATM_TERMINAL.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_TERMINAL.CREATED_DATE
     *
     * @return the value of GTW_ATM_TERMINAL.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_TERMINAL.CREATED_DATE
     *
     * @param CREATED_DATE the value for GTW_ATM_TERMINAL.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_TERMINAL.MODIFIED_BY
     *
     * @return the value of GTW_ATM_TERMINAL.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_TERMINAL.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for GTW_ATM_TERMINAL.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_TERMINAL.MODIFIED_DATE
     *
     * @return the value of GTW_ATM_TERMINAL.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_TERMINAL.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for GTW_ATM_TERMINAL.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_TERMINAL.DELETED_BY
     *
     * @return the value of GTW_ATM_TERMINAL.DELETED_BY
     */
    public String getDELETED_BY() {
        return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_TERMINAL.DELETED_BY
     *
     * @param DELETED_BY the value for GTW_ATM_TERMINAL.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY) {
        this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_TERMINAL.DELETED_DATE
     *
     * @return the value of GTW_ATM_TERMINAL.DELETED_DATE
     */
    public Date getDELETED_DATE() {
        return DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_TERMINAL.DELETED_DATE
     *
     * @param DELETED_DATE the value for GTW_ATM_TERMINAL.DELETED_DATE
     */
    public void setDELETED_DATE(Date DELETED_DATE) {
        this.DELETED_DATE = DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_TERMINAL.TERMINAL_CODE
     *
     * @return the value of GTW_ATM_TERMINAL.TERMINAL_CODE
     */
    public String getTERMINAL_CODE() {
        return TERMINAL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_TERMINAL.TERMINAL_CODE
     *
     * @param TERMINAL_CODE the value for GTW_ATM_TERMINAL.TERMINAL_CODE
     */
    public void setTERMINAL_CODE(String TERMINAL_CODE) {
        this.TERMINAL_CODE = TERMINAL_CODE == null ? null : TERMINAL_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_TERMINAL.INTERFACE_CODE
     *
     * @return the value of GTW_ATM_TERMINAL.INTERFACE_CODE
     */
    public BigDecimal getINTERFACE_CODE() {
        return INTERFACE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_TERMINAL.INTERFACE_CODE
     *
     * @param INTERFACE_CODE the value for GTW_ATM_TERMINAL.INTERFACE_CODE
     */
    public void setINTERFACE_CODE(BigDecimal INTERFACE_CODE) {
        this.INTERFACE_CODE = INTERFACE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_TERMINAL.EXPRESSION
     *
     * @return the value of GTW_ATM_TERMINAL.EXPRESSION
     */
    public String getEXPRESSION() {
        return EXPRESSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_TERMINAL.EXPRESSION
     *
     * @param EXPRESSION the value for GTW_ATM_TERMINAL.EXPRESSION
     */
    public void setEXPRESSION(String EXPRESSION) {
        this.EXPRESSION = EXPRESSION == null ? null : EXPRESSION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_TERMINAL.TELLER_USER_ID
     *
     * @return the value of GTW_ATM_TERMINAL.TELLER_USER_ID
     */
    public String getTELLER_USER_ID() {
        return TELLER_USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_TERMINAL.TELLER_USER_ID
     *
     * @param TELLER_USER_ID the value for GTW_ATM_TERMINAL.TELLER_USER_ID
     */
    public void setTELLER_USER_ID(String TELLER_USER_ID) {
        this.TELLER_USER_ID = TELLER_USER_ID == null ? null : TELLER_USER_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_ATM_TERMINAL.ACQUIRER_ID
     *
     * @return the value of GTW_ATM_TERMINAL.ACQUIRER_ID
     */
    public BigDecimal getACQUIRER_ID() {
        return ACQUIRER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_ATM_TERMINAL.ACQUIRER_ID
     *
     * @param ACQUIRER_ID the value for GTW_ATM_TERMINAL.ACQUIRER_ID
     */
    public void setACQUIRER_ID(BigDecimal ACQUIRER_ID) {
        this.ACQUIRER_ID = ACQUIRER_ID;
    }
}