package com.path.atm.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class GTW_PWS_TMPLT_USRVO extends BaseVO {
    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TMPLT_USR.CHANNEL_ID
     */
    private BigDecimal CHANNEL_ID;

    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TMPLT_USR.TEMPLATE_ID
     */
    private BigDecimal TEMPLATE_ID;

    /**
     * This field corresponds to the database column DGTL_GTW_PWS_TMPLT_USR.USER_ID
     */
    private String USER_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TMPLT_USR.CHANNEL_ID
     *
     * @return the value of DGTL_GTW_PWS_TMPLT_USR.CHANNEL_ID
     */
    public BigDecimal getCHANNEL_ID() {
        return CHANNEL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TMPLT_USR.CHANNEL_ID
     *
     * @param CHANNEL_ID the value for DGTL_GTW_PWS_TMPLT_USR.CHANNEL_ID
     */
    public void setCHANNEL_ID(BigDecimal CHANNEL_ID) {
        this.CHANNEL_ID = CHANNEL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TMPLT_USR.TEMPLATE_ID
     *
     * @return the value of DGTL_GTW_PWS_TMPLT_USR.TEMPLATE_ID
     */
    public BigDecimal getTEMPLATE_ID() {
        return TEMPLATE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TMPLT_USR.TEMPLATE_ID
     *
     * @param TEMPLATE_ID the value for DGTL_GTW_PWS_TMPLT_USR.TEMPLATE_ID
     */
    public void setTEMPLATE_ID(BigDecimal TEMPLATE_ID) {
        this.TEMPLATE_ID = TEMPLATE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DGTL_GTW_PWS_TMPLT_USR.USER_ID
     *
     * @return the value of DGTL_GTW_PWS_TMPLT_USR.USER_ID
     */
    public String getUSER_ID() {
        return USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DGTL_GTW_PWS_TMPLT_USR.USER_ID
     *
     * @param USER_ID the value for DGTL_GTW_PWS_TMPLT_USR.USER_ID
     */
    public void setUSER_ID(String USER_ID) {
        this.USER_ID = USER_ID == null ? null : USER_ID.trim();
    }
}